### ISSUE TITLE
autoUpdater does not work properly.

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#10]
```
Update error: Code signature at URL file:///Users/lamqu01/Library/Caches/com.webcatalog.app.ShipIt/update.zxHBM1P/WebCatalog.app/ did not pass validation: code failed to satisfy specified code requirement(s)
```

**Comment by quanglam2807** [comment]
electron-userland/electron-builder#1098

**Comment by quanglam2807** [comment]
Related to afterPack script. 

```js
// Use alternative exec to allow launching multiple instance of WebCatalog
const fakeExecPath = `${appOutDir}/WebCatalog.app/Contents/MacOS/WebCatalog`;
const realExecPath = `${appOutDir}/WebCatalog.app/Contents/MacOS/WebCatalog_Real`;

return new Promise((resolve, reject) => {
  execFile('./build/generate_alt_exec.sh', [
    fakeExecPath,
    realExecPath,
  ], (err, stdout) => {
    console.log(err);
    console.log(stdout);

    if (err) {
      reject(err);
      return;
    }

    resolve();
  });
});
```

https://developer.apple.com/library/content/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG311

> Store Python, Perl, shell, and other script files and other non-Mach-O executables in your app's Contents/Resources directory. While it's possible to sign such executables and store them in Contents/MacOS, this is not recommended.

**Comment by natrim** [comment]
thats fixable by using binary instead of bash script
ie. golang binary: https://gist.github.com/natrim/04a0324ca6898619fad5579ef1facb68
compiled there: https://www.dropbox.com/s/yogkelfvkvrea65/Webcatalog?dl=1

(or you could use Swift or Rust or even C)

**Comment by quanglam2807** [comment]
@natrim I tried a similar method. It fixed the signing issue but it still doesn't work somehow. I'll test again with your code soon. It'd be better if there's an API or something to modify the behavior with code instead of dealing with a file hack like this.

**Comment by quanglam2807** [comment]
@natrim Better solution: Simply duplicate the executable file, but all the apps have to update to link to the duplicated executable. I don't remember why I did not do this (maybe to keep the apps' compatibility)

**Comment by natrim** [comment]
to the Better solution

seems to work for me, 
i just duplicated the WebCatalog_Real as Webcatalog
renamed the old WebCatalog_Real as WebCatalogLauncher
and resigned the app
then i changed the shortcut apps to use the WebCatalogLauncher
and it works

Edit: evidence here: https://www.dropbox.com/s/ispdn7uu5tvh7op/Archiv.zip?dl=1

**Comment by quanglam2807** [comment]
@natrim The reason why I do it is because when you launch an app from Launchpad, if macOS detects that the executable is running, it won't start a new instance. In the case of WebCatalog, all the apps installed from it is actually just a script to open a new instance of WebCatalog executable file with some parameters. Because of this design, for example, if you are opening Messenger and try to open WebCatalog from Launchpad, it won't start because Apple thinks the executable is already running. 

With the current solution, using a script file as main executable, WebCatalog is able to trick macOS. macOS will think the executable file of the app is "WebCatalog" while the real one is "WebCatalog_Real". And because the script file only runs to call the real one and then exit, macOS will think WebCatalog is not running and start the app. 

This is what we need to resolve.

**Comment by quanglam2807** [comment]
@natrim Haha, whatever. Duplicating the executable seems working for me.

**Comment by quanglam2807** [comment]
#43 3.1.1 is up with auto updater :)
