### ISSUE TITLE
Losing Input/Textarea Focus on Changing Active Window

### ISSUE THREAD

**Issue by fatihturan** [quanglam2807/appifier#101]
I'm losing focus on textarea (or input) field if I change the current Webcatalog app to another some Mac App and returning again to Webcatalog app. I created [a screencast for this problem](https://cl.ly/jzrj).

**Comment by tmeusburger** [comment]
I experience the same thing but not just on text area or input fields. The focus seems to shift away from the webview completely so if I alt+tab to a window I can't initiate keyboard shortcuts.

An example of this is on macos, when I tab to the soundcloud application I can't use space to start/pause the music without first clicking on the window with the mouse.

**Comment by quanglam2807** [comment]
I moved this issue to a new repo: https://github.com/webcatalog/molecule/issues/7

**Comment by swrobel** [comment]
@quanglam2807 it seems that the molecule repo doesn't exist anymore. I'm still seeing this issue on 6.4.1, macOS 10.13

**Comment by quanglam2807** [comment]
@swrobel The link didn't work because the project was private. You can access it now.

We haven't fixed the issue but we will look into it after WebCatalog 7's release.

**Comment by fatihturan** [comment]
I hope this issue will be fixed in next release. :) Cuz sometimes it's really annoying me. :)

**Comment by swrobel** [comment]
Electron issue with workarounds for reference: https://github.com/electron/electron/issues/5900

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by quanglam2807** [comment]
@swrobel Thanks a lot for the reference. I've made the commit but I'm not sure if it would fix the problem. I tested on my Macbook and it worked. :)
