### ISSUE TITLE
Provide an Option to Enable Right Click Menu

### ISSUE THREAD

**Issue by fatihturan** [quanglam2807/appifier#102]
Sometimes I need default right click menu on some Webcatalog apps. Can you provide an option to enable right click menu?

**Comment by quanglam2807** [comment]
@fatihturan What should I add in the right click menu?

**Comment by fatihturan** [comment]
Hi, menu items could be:

- Back/Forward
- Copy Selected URL
- Copy Current URL

Thanks for your interest.

**Comment by natrim** [comment]
just thing that is not really relevant to this but it works and i use it:

you can make your own menu thanks to the js injection
example menu (just open setting and put it in the inject js textarea):

`var wrap = document.createElement("DIV");
wrap.style.display = "none";
wrap.style.position = "fixed";
wrap.style.top = "50%";
wrap.style.left = "50%";
wrap.style.webkitTransform = "translate(-50%, -50%)";
wrap.style.transform = "translate(-50%, -50%)";
wrap.style.background = "#00f6ff";
wrap.style.zIndex = 999999;
wrap.style.padding = "5px";
wrap.style.borderRadius = "10px";
wrap.innerHTML = "<a id=\"rclk_menu_back\" style=\"cursor: hand; cursor: pointer\">&lt; BACK</a> - <a id=\"rclk_menu_top\" style=\"cursor: hand; cursor: pointer\">^ TOP</a> - <a id=\"rclk_menu_forward\" style=\"cursor: hand; cursor: pointer\">FORWARD &gt;</a>";
document.body.append(wrap);
document.getElementById("rclk_menu_back").addEventListener('click', function(ev) {
    ev.preventDefault();
    window.history.go(-1);
    return false;
}, false);
document.getElementById("rclk_menu_forward").addEventListener('click', function(ev) {
    ev.preventDefault();
    window.history.go(+1);
    return false;
}, false);
document.getElementById("rclk_menu_top").addEventListener('click', function(ev) {
    ev.preventDefault();
    window.scrollTo(0,0);
    return false;
}, false);
document.addEventListener('contextmenu', function(ev) {
    ev.preventDefault(); 
    wrap.style.display = "block";
    return false;
}, false);
document.addEventListener('click', function() {    
    wrap.style.display = "none";
}, false);
`

![schranka 01](https://cloud.githubusercontent.com/assets/488136/25564848/474075f8-2dbc-11e7-9297-8ea2cdf3bb5f.png)
