### ISSUE TITLE
Recommend Change Office 365 Outlook Web App Icon

### ISSUE THREAD

**Issue by Paulser** [quanglam2807/appifier#104]
I recommend you change icon for the web app: 

Office 365 Outlook
outlook.office365.com

This is to similar to Outlook.com > outlook.live.com. 

This is not great if you are using both. 

Since Office 365 Outlook kinda has Exchange backend you could use that icon. Exchange Online uses this icon which is just Office 365 sort off.

![images](https://cloud.githubusercontent.com/assets/20326940/25020260/857407a2-2085-11e7-931d-574907e54bd9.png)

**Comment by quanglam2807** [comment]
@natrim Can you have a look?
