### ISSUE TITLE
Adds FIDO U2F support

### ISSUE THREAD

**Issue by Paulser** [quanglam2807/appifier#105]
This just feature request if this could be possible. 

Dont expect this soon at all.

https://www.yubico.com/about/background/fido/

**Comment by quanglam2807** [comment]
@Paulser It has Chrome extension so it is possible. https://chrome.google.com/webstore/detail/fido-u2f-universal-2nd-fa/pfboblefjcgdjicmnffhdgionmgcdmne/reviews?hl=en

**Comment by Paulser** [comment]
Sounds great not sure what causing me this issue then. The webcatalog apps do not seem to recognise FIDO U2F is an option or there is an issue on the linux version have not tried windows. Github account fails and the Fastmail just uses text instead. 

Tested on v4.1.12

![spectacle h18683](https://cloud.githubusercontent.com/assets/20326940/25578130/a6b945a8-2e63-11e7-9cc8-8970c213ea29.png)

![spectacle j20185](https://cloud.githubusercontent.com/assets/20326940/25578134/aaa3d23c-2e63-11e7-8344-905c96a8793c.png)

**Comment by quanglam2807** [comment]
@Paulser Currently, WebCatalog uses Electron as its framework. It still uses Chromium as the core but many Chrome APIs are removed. I am working to move the framework to muon which Brave Browser is using. By doing that, it would be much more usable as a browser.

**Comment by quanglam2807** [comment]
I moved this issue to a new repo: https://github.com/webcatalog/molecule/issues/6
