### ISSUE TITLE
Installing an app immediately shows an update is available

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#108]
WebCatalog 4.1.10
macOS 10.12.4

Installed Tweetdeck just now, update button appears. Click update button. Progress bar appears for a second. Update button reappears. All of my installed apps show the update button, but it doesn't seem to do anything.

**Comment by quanglam2807** [comment]
@swrobel Thank you for reporting. Should be fixed with https://github.com/webcatalog/webcatalog/commit/d050821660664d6fff07ae4a38035615863d7f16 and 4.1.11
