### ISSUE TITLE
Installed apps are not rediscovered properly when reinstalling WebCatalog

### ISSUE THREAD

**Issue by adambowles** [quanglam2807/appifier#110]
OS: Fedora Linux 4.4.14-200.fc22.x86_64
Gnome-shell version: GNOME Shell 3.16.4
WebCatalog version: 4.1.11

Installed via `.rpm` package

Installed some apps via WebCatalog, and they get shown in the WebCatalog `installed` dashboard, as expected. These apps can also be found using Gnome Shell

When removing WebCatalog via Fedora's software manager and reinstalling the `.rpm` package, WebCatalog's apps are not in the `installed` dashboard, but can be found using Gnome Shell

Here I have done this process twice with WhatsApp:
![screenshot from 2017-04-18 12-03-18](https://cloud.githubusercontent.com/assets/10128574/25127779/16e6c72c-242f-11e7-8329-89ac51fb4419.png)

See nothing in WebCatalog:
![screenshot from 2017-04-18 12-03-27](https://cloud.githubusercontent.com/assets/10128574/25127788/1e8ffe12-242f-11e7-8ab6-a4978d3f7eba.png)

**Comment by adambowles** [comment]
Where are the WebCatalog apps stored in Linux, so I can manually remove and reinstall them?

Edit: Found install location (`~/.local/share/applications`) via https://github.com/webcatalog/webcatalog/releases/tag/v4.1.5

**Comment by quanglam2807** [comment]
@adambowles Did you manage to fix it? I am sorry. It was because of a bad technical decision in the beginning.

**Comment by adambowles** [comment]
Nope, I can't get it to rediscover previously installed apps through a reinstall

I discovered originally this through updating the app, but thought that was due to the 4.1.5 linux breaking change

**Comment by quanglam2807** [comment]
@adambowles So even if you reinstall the app, it won't work?

**Comment by adambowles** [comment]
Correct

**Comment by quanglam2807** [comment]
@adambowles I cannot launch WebCatalog after installation. Did you have similar issue?

**Comment by adambowles** [comment]
@quanglam2807 I've not encountered that

**Comment by adambowles** [comment]
Nice, I'll test next release when it is available @quanglam2807

**Comment by quanglam2807** [comment]
@adambowles Please test https://github.com/webcatalog/webcatalog/releases/tag/v4.1.12

**Comment by adambowles** [comment]
@quanglam2807 Yep works as expected, it found my installed apps after updating
