### ISSUE TITLE
DeviantArt is misspelled

### ISSUE THREAD

**Issue by adambowles** [quanglam2807/appifier#111]
![screen shot 2017-04-23 at 21 14 20](https://cloud.githubusercontent.com/assets/10128574/25317102/db2c78fa-2869-11e7-8624-1d10ac1f5357.png)
"DevianArt" instead of "Devian**t**Art"

**Comment by quanglam2807** [comment]
@adambowles https://github.com/webcatalog/webcatalog-backend/commit/7b379dca55a860b9165d5027ad183587a39e6f11

**Comment by quanglam2807** [comment]
I am rewriting the backend so I won't change the `id` of the app as the old backend repo will be obsolete soon.
