### ISSUE TITLE
Hides menu bar

### ISSUE THREAD

**Issue by rhoconlinux** [quanglam2807/appifier#112]
Hi there, 

It would be awesome (and apparently not difficult at all) to include an option in "View" menu to hide the menu. This contributes to get a neat integration in any OS and theme/mod used in each particular environment. 

Typically this function is associated with F8 or F11 keys (show/hide menu). Hope we can get it!

Thanks in advance and good work!

**Comment by quanglam2807** [comment]
@rhoconlinux It won't be too difficult to implement. But right now, as I am rewriting the backend server, it will take a while until the next major release.

**Comment by quanglam2807** [comment]
@rhoconlinux I remember that Firefox and Chrome used to have a keyboard combination to hide/show the menu. Does it sound sufficient for you?

**Comment by rhoconlinux** [comment]
@quanglam2807 yes! that would be AWESOME! 
Thanks for the feedback and the continuous work.
Cheers!

**Comment by quanglam2807** [comment]
@rhoconlinux I'll resolve this issue in version 5.1.
