### ISSUE TITLE
Adds option to create custom apps

### ISSUE THREAD

**Issue by poochie89** [quanglam2807/appifier#113]
There does not seem to be an option to create Apps/Websites if they are not listed.
Would be nice, not all of my websites are available. Btw. I am aware of the "submit app" possibility.

**Comment by quanglam2807** [comment]
#12 

I have implemented the feature before but decided to remove it as the libraries the app relied on were not stable enough. It'll be back with 5.0.

**Comment by stadtkonzeptbasel** [comment]
hey @quanglam2807 any news on that? For me the reason i'm still on fluidapp...

**Comment by quanglam2807** [comment]
@poochie89 We will work on this issue after WebCatalog 7
