### ISSUE TITLE
Confirmation dialog on app uninstall

### ISSUE THREAD

**Issue by natrim** [quanglam2807/appifier#114]
It would be nice to have confirmation dialog on custom app uninstall.

(Today i accidentally removed app, instead on clicking on open and it removed all my data...)

**Comment by quanglam2807** [comment]
<img width="415" alt="screen shot 2017-05-22 at 11 53 35 pm" src="https://cloud.githubusercontent.com/assets/1548835/26338945/e5096576-3f49-11e7-857b-0e27247af50c.png">

Done :)
