### ISSUE TITLE
 Downloading files without extensions

### ISSUE THREAD

**Issue by ghost** [quanglam2807/appifier#117]
Sorry, my English is not the best...

Websites like Facebook and Gmail allow you to save files. Unfortunately, when saving these files from the webcatalog does not appear extension and need to manually add. The problem is all files, not just photos or documents.

**Comment by quanglam2807** [comment]
@Gandalf888 What OS are you using? I tested the app on Mac and it works normally for me.

**Comment by ghost** [comment]
@quanglam2807 Windows 10. Below is a link from the download window from gmail. WebCatalog version 5.1.1
http://wstaw.org/m/2017/05/21/catalog.png

**Comment by quanglam2807** [comment]
I moved this issue to a new repo: https://github.com/webcatalog/molecule/issues/5
