### ISSUE TITLE
Tmetric doesn't work

### ISSUE THREAD

**Issue by balmes-io** [quanglam2807/appifier#118]
That is the screen I get after login in Tmetric App
![captura de pantalla 2017-05-17 a las 8 48 22](https://cloud.githubusercontent.com/assets/3216169/26141753/b91a4ac2-3add-11e7-9332-a437a52052b5.png)

**Comment by quanglam2807** [comment]
@balmes-io WebCatalog rendering engine is not fully Chrome-like so it causes this issue. I'll try to fix it ASAP.

**Comment by quanglam2807** [comment]
I close this to clean up issues. This problem is related to https://github.com/electron/electron/issues/8969
