### ISSUE TITLE
inject js and css no longer working

### ISSUE THREAD

**Issue by natrim** [quanglam2807/appifier#121]
Seems like v5 broke the injection of js and css from settings into page

**Comment by quanglam2807** [comment]
Fixed :)

**Comment by natrim** [comment]
thx for fix

but there seems to be little bug in the code .)
on https://github.com/webcatalog/webcatalog/blob/5ce838caff93ef950bb4e234d5f409faeaa5a24d/src/main/preload.js#L10

if there is no js then it returns and the css is not injected

**Comment by natrim** [comment]
plus using innerHTML triggers CSP and prevents load on some apps (ie. DropBox Paper)

( Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' )

**Comment by quanglam2807** [comment]
@natrim Thank you natrim. I'll fix it.
