### ISSUE TITLE
Twitter 2FA login redirect broken again

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#122]
WebCatalog 5.2.0
macOS 10.12.5

I get texted a 2FA code, but WebCatalog doesn't redirect to the screen to enter it. I don't see any errors/warnings in console, but I do see this request in Network.
<img width="625" alt="screen shot 2017-05-31 at 8 57 21 am" src="https://cloud.githubusercontent.com/assets/157270/26641369/384ac342-45df-11e7-8b8f-8e114268b408.png">

**Comment by quanglam2807** [comment]
It's related to this issue: https://github.com/electron/electron/issues/3471

Electron doesn't reproduce the sandboxed environment of Chrome correctly so it causes a lot of problems.

**Comment by quanglam2807** [comment]
I close this to clean up issues. This problem is related to https://github.com/electron/electron/issues/8969
