### ISSUE TITLE
Vertically center window controls on macOS

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#126]
Window controls are top-aligned which looks weird compared to the toolbar icons
<img width="211" alt="screen shot 2017-06-20 at 4 48 58 pm" src="https://user-images.githubusercontent.com/157270/27360857-913f6292-55d8-11e7-9da4-389ab2fc7558.png">

Similar Electron apps do this.
Atom (in custom-inset Title Bar mode):
<img width="145" alt="screen shot 2017-06-20 at 4 50 59 pm" src="https://user-images.githubusercontent.com/157270/27360881-b3ccbf44-55d8-11e7-9fff-ce53f7c285b4.png">

WhatsApp:
<img width="132" alt="screen shot 2017-06-20 at 4 51 51 pm" src="https://user-images.githubusercontent.com/157270/27360896-c825f348-55d8-11e7-9e7e-56710d1466f0.png">

**Comment by quanglam2807** [comment]
<img width="558" alt="screen shot 2017-06-20 at 9 16 30 pm" src="https://user-images.githubusercontent.com/1548835/27364053-c1702b70-55fd-11e7-8ad2-088e579d929a.png">

If I change it, with the current design, the nav bar will be too big. I'll make this change together with some design changes in v7.

**Comment by quanglam2807** [comment]
![screen shot 2017-06-24 at 11 23 24 pm](https://user-images.githubusercontent.com/1548835/27513651-25c940f0-5934-11e7-9fe0-a0c5c973cc52.png)

It has been fixed in 7.0 👍
