### ISSUE TITLE
Desktop sharing extension - denied

### ISSUE THREAD

**Issue by vlad-cotfas** [quanglam2807/appifier#137]
Hello,

I have an app called ChatApp.app

I use this WebCatalog and ChatApp.app on a Mac for a chat/desktop sharing environment (site URL)

The chat site only works with Google Chrome and it has a Google Chrome Extension for live desktop sharing

From what I saw in the background.js and rename file it uses this https://github.com/jitsi/jidesha extension for Live Screen Sharing

When I`m trying to open the screen sharing functionality I get an error with "Permission denied - Failed to install desktop sharing extension"

<img width="404" alt="screenshot at jun 27 21-38-40" src="https://user-images.githubusercontent.com/3340367/27604294-90e95286-5b81-11e7-8ad9-e07fae7685cc.png">

Where can I move the extension (Chrome extension) files and link with the Chat App in order for this to work? 

Maybe in the App folder structure:
z:\Users\username\Applications\WebCatalog Apps\ChatApp.app\Contents\Resources\ ??

Or how I can force the WebCatalog Chat App to accept installing that extension? (Or force to accept any permission requests)

PS: I did not create ChatApp.app. I`m using an already made app from the WebCatalog and edited in settings to use my URL

Edit:
====================================
I see from the GitHub for that extension it is based on

Note: this extension relies on the Chrome chooseDesktopMedia API which requires HTTPS.

https://developer.chrome.com/extensions/desktopCapture
====================================

Thank you very much in advance!
Best regards, Cotfas

**Comment by cotfas** [comment]
I see from the github for that extension it is based on 

Note: this extension relies on the Chrome chooseDesktopMedia API which requires HTTPS.

https://developer.chrome.com/extensions/desktopCapture

**Comment by quanglam2807** [comment]
I'll will close this issue as it's related to https://github.com/webcatalog/molecule/issues/4
