### ISSUE TITLE
Block an custom URL to be opened on Safari

### ISSUE THREAD

**Issue by vlad-cotfas** [quanglam2807/appifier#138]
Hello,

I have an app called ChatApp.app

I use this WebCatalog and ChatApp.app on a Mac for a chat/desktop sharing environment (site URL)

When I'm initiating a Live Chat from Site URL, the URL for the Live environment is opened in Google Chrome in a new tab. When I'm using the ChatApp.app via WebCatalog, and initiate a Live Chat the environment is opened in a new window, which is good but also is forced to open that link in Safari. How can I disable/force the WebCatalog App that when I`m opening the Live, the URL link to not be opened in Safari? 

PS: I did not create ChatApp.app. I`m using an already made app from the WebCatalog and edited in settings to use my URL

Thank you very much in advance!
Best regards, Cotfas

**Comment by quanglam2807** [comment]
This problem is related to https://github.com/electron/electron/issues/8969.
