### ISSUE TITLE
Add pause/play/skip key bindings on media

### ISSUE THREAD

**Issue by onlineth** [quanglam2807/appifier#155]
Add pause/play/skip key bindings on apps that have audio content being played (this feature is in particular to PocketCasts but should be applied to other apps as well). A starting point could be to use https://github.com/berrberr/streamkeys as a template and tap into Window's media control overlay.

![Imgur](https://i.imgur.com/We2nIVz.png)

**Comment by quanglam2807** [comment]
@onlineth Thanks a lot! We will try implement this feature. Right now, we are still working on WebCatalog 7 #127

**Comment by onlineth** [comment]
@quanglam2807 Great to hear, I don't know much about Electron but if anyone knows of another Electron project that was able to work with the Windows's media control overlay, I could try and replicate that feature here myself.

**Comment by onlineth** [comment]
Has this been or will be implemented?

**Comment by quanglam2807** [comment]
@onlineth The project is almost dead. I'm trying to save it. I'll try to check and reopen the issues in the future.
