### ISSUE TITLE
Problems with Wacom tablet 

### ISSUE THREAD

**Issue by superlativ0** [quanglam2807/appifier#156]
Sometimes WebCatalog loses the Wacom tablet connection. This works perfectly with the rest of the OS and other programs but with the programs of WebCatalog the pen can not click. Instead the keyboard and mouse do work.

Although I close and reopen the problem persists.

Mac Pro (2009)
macOS Sierra 10.12.6
Wacom Intuos Pen & Touch (CTH-480)

Thanks in advance.

**Comment by quanglam2807** [comment]
@superlativo77 Thanks a lot for the feedback. Does the pen work with the main WebCatalog app?

**Comment by superlativ0** [comment]
Hi @quanglam2807 

Sorry, I can't try now because works correctly. When I will have the problem again I will try.

Thanks
