### ISSUE TITLE
Add Find in page support

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#16]
`Ctrl+F` on Windows or `⌘+F` on Mac. This is one essential feature that Fluid has that WebCatalog doesn't seem to.

Awesome work, though, I've been looking for a Fluid replacement for ages, and this is definitely the closest I've found!

**Comment by swrobel** [comment]
Electron API I believe will need to be used: http://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options

Example code: https://github.com/edulan/electron-search-example
Another, more complete example: https://github.com/nakajmg/electron-search-text
Possibly ready-to-use package: https://github.com/rhysd/electron-in-page-search

**Comment by quanglam2807** [comment]
Thank you very much, @swrobel! rhysd/electron-in-page-search looks great! I'll start working on this soon.

**Comment by quanglam2807** [comment]
@swrobel Trickier than what I expected. The package relies on some Node APIs but it's not possible to run Node in the app container because it conflicts with some sites, including messenger.com.

The solution is to rewrite the package or use webview. But I'm not really sure.
