### ISSUE TITLE
Add notification support

### ISSUE THREAD

**Issue by micheljung** [quanglam2807/appifier#161]
Maybe I missed something, but I wasn't able to get this running.

Apps like WhatsApp and Facebook make use of notifications (the little popups in the bottom right). Such notifications do not seem to work with WebCatalog.

I'm using the latest WebCatalog on Windows.

**Comment by quanglam2807** [comment]
@micheljung Thanks a lot for reporting. This is a known bug. Hopefully, it'll be fixed in WebCatalog 7.

**Comment by quanglam2807** [comment]
@micheljung WebCatalog 7 is now available. Can you test to see if it works correctly?

**Comment by vlad-cotfas** [comment]
I`m having the same issue on Mac

I have the WebCatalog 7.0.7

And when I`m receiving a notification from Whatsapp (for example) I do not see the badge counter in the taskbar icon. On WebCatalog 6.4 it was working.

**Comment by micheljung** [comment]
@quanglam2807 I tested with WhatsApp; Sound works, but I don't see a notification popup. I checked the settings in WhatsApp and they are turned on.

**Comment by quanglam2807** [comment]
@cotfas @micheljung Can you guys test again with v7.0.11?

**Comment by micheljung** [comment]
WebCatalog Version 7.0.11, latest WhatsApp version, Desktop alerts enabled, WhatsApp minimized, no desktop notification.

**Comment by quanglam2807** [comment]
> Hey. Thanks again for the amazing work and development!
Currently I'm not seeing any notifications on my desktop for new emails in gmail. Is this supposed to be available? Is there something I need do?

**Comment by quanglam2807** [comment]
Guys, does notification work in any app?

**Comment by vlad-cotfas** [comment]
For me it is working

I`m using the 7.4 version
