### ISSUE TITLE
Twitter 2FA login redirect broken

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#162]
Same issue as last time: https://github.com/webcatalog/webcatalog/issues/122

Manually navigating to the failed redirect via devtools console `window.location =` resolves the issue temporarily.

Loving WebCatalog 7.0 so far! I wish this wasn't such a hassle for you to fix all the time.

Webcatalog 7.0.7 on macOS 10.13

**Comment by quanglam2807** [comment]
@swrobel It seems like a hacky fix. electron/electron#3471 

I'll try to make a pre-release soon.

**Comment by quanglam2807** [comment]
Hopefully, it will work :)
