### ISSUE TITLE
Unable to uninstall Deezer

### ISSUE THREAD

**Issue by demicon** [quanglam2807/appifier#167]
I am getting "We're sorry. WebCatalog has failed to uninstall Deezer." error displaying at the bottom when I try to uninstall deezer. Tried closing and reopening the webcatalog app. Still the error persists

**Comment by quanglam2807** [comment]
@demicon What OS are you using?

**Comment by demicon** [comment]
Windows 10

**Comment by demicon** [comment]
![image](https://user-images.githubusercontent.com/26656849/31863260-fdf2f966-b768-11e7-81f2-997b3fe45585.png)

**Comment by quanglam2807** [comment]
@demicon Can you try to uninstall the app, then open press Alt, choose View > Toggle Developer Tools. Then send me the log.

**Comment by demicon** [comment]
![image](https://user-images.githubusercontent.com/26656849/31863356-2bb7288a-b76a-11e7-925b-672294e15837.png)

**Comment by demicon** [comment]
does this help?

**Comment by demicon** [comment]
The Object(code EBUSY... and Error:Uninstalling Failed appears, everytime I click uninstall

**Comment by quanglam2807** [comment]
@demicon Did you quit Deezer first?

**Comment by demicon** [comment]
Yeah Deezer is quit. I also restarted Webcatalog

**Comment by quanglam2807** [comment]
@demicon I'm sorry but I think the best solution is to restart your computer.

**Comment by demicon** [comment]
Thanks! It uninstalls after restarting my computer

**Comment by quanglam2807** [comment]
@demicon I'm glad it works for you!
