### ISSUE TITLE
Twitter DMs with images redirect to the image

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#173]
This is very odd behavior. Here are steps to reproduce:

1. Open Twitter app
1. Click Messages in the top Nav of the website
1. Open a DM conversation where an image has been shared by uploading it
1. Note that the conversation briefly shows before the view is redirected to show the image itself. The only way to get out of this view is to go to View > Force Reload.

Here are devtools logs from when this happened to me just now:

```
Resource interpreted as Document but transferred with MIME type image/jpeg: "https://ton.twitter.com/i/ton/data/dm/850361309480706051/850361299535921153/tymHlRxl.jpg:large".
Navigated to https://ton.twitter.com/i/ton/data/dm/850361309480706051/850361299535921153/tymHlRxl.jpg:large
```

**Comment by quanglam2807** [comment]
@swrobel Have you tested it with Chrome?

**Comment by swrobel** [comment]
@quanglam2807 yes I meant to mention but forgot, I tested in Chrome and it behaves as expected. No bug.

**Comment by quanglam2807** [comment]
This Issue is related to electron webview. So let's wait for Electron 1.8. :)
