### ISSUE TITLE
"Update is available" message appears on all installed apps, even after webcatalog is updated

### ISSUE THREAD

**Issue by demicon** [quanglam2807/appifier#178]
![image](https://user-images.githubusercontent.com/26656849/32295019-0140250a-bf6e-11e7-86fe-617e3237aa2f.png)

Edit: Tried restarting pc, still the message persists

**Comment by quanglam2807** [comment]
@demicon You need to go to Installed Apps to update installed apps. I'll try to improve the UI to make it easier to use.
