### ISSUE TITLE
Twitter sometimes tries to download ad.mpg on Home feed

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#182]
This comes up occasionally when I'm on my Home feed. I have to cancel it out about 5 times before it goes away for good. The only thing in my Console is

`twitterinitmatch Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

<img width="720" alt="screen shot 2017-11-09 at 4 12 24 pm" src="https://user-images.githubusercontent.com/157270/32636303-0a61e9ce-c569-11e7-9f7d-e8a53d061425.png">

I think it might be related to the "Live video" feed:
<img width="296" alt="screen shot 2017-11-09 at 4 18 53 pm" src="https://user-images.githubusercontent.com/157270/32636468-c8a60640-c569-11e7-950b-9414643def71.png">

**Comment by quanglam2807** [comment]
It seems like Twitter doesn't work well with Electron at all. Let's wait for Electron 1.8.

**Comment by swrobel** [comment]
Yes, there are definitely some strange issues. Here is another: sometimes it refreshes and just shows this until I do a Force Reload
<img width="390" alt="screen shot 2017-11-13 at 12 30 25 pm" src="https://user-images.githubusercontent.com/157270/32747764-9f4f4e52-c86e-11e7-93ac-26cb90455131.png">

**Comment by quanglam2807** [comment]
This Issue is related to electron webview. So let's wait for Electron 1.8.  :)
