### ISSUE TITLE
Multiple instances of an app

### ISSUE THREAD

**Issue by SchwartzWare** [quanglam2807/appifier#183]
It would be nice if you could have multiple instances of an app. It would be extremly usefull if you have multiple accounts on a platform and dont have to logout, login all the time.

**Comment by quanglam2807** [comment]
I did work on a prototype for this feature before and I'm planning to bring it back soon.

<img width="561" alt="26956873-ab05e27e-4c86-11e7-906f-ab111f55ace0" src="https://user-images.githubusercontent.com/1548835/32652542-2e033120-c637-11e7-91ff-6f1ff9b2dac2.png">

**Comment by jonshayler** [comment]
+1 for this please!

**Comment by Jason-Morcos** [comment]
+1 as well. Multiple windows/tabs support macOS native style would be amazing
