### ISSUE TITLE
Keep the Project running

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#184]
As an international student in the US, it's not possible to sell the app or receive donations from the community (F1 visa's regulations). Additionally, I'm planning to concentrate less on software development to concentrate on my school works.

But the number of WebCatalog's users continue to grow so I need to deal with a larger number of app submissions and traffic. So I need some help from the community.

1. A person (or persons) to approve app submissions.
2. A way to pay for the server's cost. I cannot take money donations so I would be great if somebody can provide free hosting or something similar. (WebCatalog relies on a Node.js server, Postgres, S3, CloudFront, SES).

Or even better, legal support to turn WebCatalog into a legitimate business. I did plan to offer premium plan to make profits but due to my visa status, it is very cumbersome.

**Comment by vlad-cotfas** [comment]
"A person (or persons) to approve app submissions."

Can you make a dashboard so there is more than 1 admin that will approve app submission? This way it will be more productive for app submissions.

**Comment by quanglam2807** [comment]
It's already up and running. Are you interested?

**Comment by vlad-cotfas** [comment]
I can help but it will be only in my free time. Is there any policy on what it should look the submitted Apps?

**Comment by quanglam2807** [comment]
@cotfas Awesome. There's no specific guideline but you should only approve apps you feel acceptable. Also, no porn.

**Comment by demicon** [comment]
I can help you up with app submissions

**Comment by vlad-cotfas** [comment]
Quang, can you send me in private the login details and credentials please

**Comment by quanglam2807** [comment]
@demicon cotfas Thanks a lot, guys! Please email me quang@webcatalog.io your login email you use for WebCatalog account.
