### ISSUE TITLE
Improve Icon quality

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#185]
> Ian Jukes: Hey Quang — I’ve noticed that all the icons are very poor quality when scaled up? They are fine when small in the dock but look terrible when larger, like in Launchpad or when the dock is magnified. Is there anything you can do about this? It’s not just an issue with the 500px icon.

> Quang Lam: Hi Ian,
Sadly, it's hard to find a solution for this issue. The icons on Google Play and App Store are all at 512x512px while the ones on Twitter are all at 400x400px. To have good icons for Mac, we need 1024x1024px icons which are extremely hard to find.

**Comment by ianjukes** [comment]
Hey Quang. I'd be happy to start to source alternative icons. There are plenty out there. What size and format would they need to be? Is 1024x1024px enough? PNG?

**Comment by quanglam2807** [comment]
That would be awesome! And yes, 1024x1024px is enough :)

**Comment by ianjukes** [comment]
So I've created my first 1024x1024px PNG with transparency for Facebook, from their official logo. Where should I upload in Github?

**Comment by quanglam2807** [comment]
Yes, please. But I'm not sure if GitHub degrades the icon or not so maybe you can email it to me or share a link to cloud storage.

**Comment by ianjukes** [comment]
Hey Quang!

I’ve attached a Facebook and 500px logo. Can you update the apps with these and I will upgrade them via WebCatalog and test them? If they look okay I’ll start looking for other logos. They are both 1024x1024px PNGs with transparency.

Ian

—
Ian Jukes

**Comment by ianjukes** [comment]
Here are a bunch of others as well. I can’t find the shopping cart version of the Amazon icon, so I’ve created this generic one.

Let me know if they’re any good?

Ian

—
Ian Jukes

**Comment by quanglam2807** [comment]
#194
