### ISSUE TITLE
Webcatalog chrome visible when in fullscreen video

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#188]
When playing fullscreen video, the top bar is not hidden. 
```
Webcatalog Version 7.5.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

```

See screenshot: 
![bildschirmfoto 2017-11-11 um 23 45 30](https://user-images.githubusercontent.com/2744198/32694210-bd3f5324-c73a-11e7-9055-02241a611e46.png)

**Comment by fsdias** [comment]
In Ubuntu 16.04, with the Netflix app, the navigation bar is not hidden when in full-screen mode.

**Comment by jottr** [comment]
This is on OSX. Updated the issue accordingly.
