### ISSUE TITLE
2.7.0 Broke everything.

### ISSUE THREAD

**Issue by Rediwed** [quanglam2807/appifier#19]
Updating to 2.7.0 broke everything, neither launching the web-apps nor launching the main application works.
And since I've currently moved to WebCatalog to access all my web applications, I have a problem...

`Uncaught Exception:
Error: Cannot find module 'optimist'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/WebCatalog.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/WebCatalog.app/Contents/Resources/app.asar/main.js:4:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)`

**Comment by quanglam2807** [comment]
@Rediwed OMG! I'm working to fix it ASAP.

**Comment by Rediwed** [comment]
I havent tried resetting the applications! Could you point me to the location in which the application settings are saved? As maybe that helps!

Also; you reacted in three (3) minutes! That's the single fastest non-messenger app response I've seen anywhere, ever.

**Comment by quanglam2807** [comment]
@Rediwed Haha. There's a bug in the build process so I need to release a new update. It's my fault, not yours so don't worry.

**Comment by Rediwed** [comment]
Another one in 4 minutes phew!
Good to know, I'm looking forward to using it again!

Can't wait what the future of WebCatalog will bring!

**Comment by quanglam2807** [comment]
@Rediwed 👍 No new feature in this update. It's mostly for Linux support. But let's see.

**Comment by Rediwed** [comment]
And a fix in 31 minutes. You are a hero!
My github account is purely for reporting issues though, so as I don't know how to build the source i'll report my findings (or not if there are none) when it's released on the website ;)

**Comment by quanglam2807** [comment]
@Rediwed It's up now! Also, if you want to ask for new feature, such as Chromecast, you can create a new issue on GitHub. Better than Reddit :)

**Comment by Rediwed** [comment]
Yeah, I figured! Didn't know you had this github when I wrote that. I'll add a feature request!
