### ISSUE TITLE
Icons are not rendered correctly on Mac

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#194]
```
Okay, so something strange is going on. I’ve attached a screenshot of the new icons in LaunchPad and as you can see they are not rendering correctly. If you compare them to your WebCatalog app icon (which is rendered smoothly) you can see they have jagged edges. That makes me think there’s something in the code that’s causing the issue?

Ian
```

```
This is strange. I think you need to add some shadow. Can I send me one icon with shadow so we can test it out?
```

```
I don’t think it’s the icon. I think there’s something in the code. I have installed Fluid and created a SSB for Facebook using the same PNG I sent you and you can see from the attached screenshot that Fluid renders the Facebook icon perfectly.

However, I’ve attached the new Netflix icon for you to also try. That one has a lot of gradient etc. in the N and is not so flat.

Let me know how you get on. Glad to be helping!

Ian
```

**Comment by quanglam2807** [comment]
![screenshot_fluid](https://user-images.githubusercontent.com/1548835/32780947-b03135f2-c975-11e7-9f29-b80115010f81.png)

**Comment by quanglam2807** [comment]
<img width="190" alt="screen shot 2017-11-14 at 7 56 24 pm" src="https://user-images.githubusercontent.com/1548835/32781006-f3936efa-c975-11e7-9cf2-8a6ce08be256.png">

Even the colors are different from the one created with Fluid.

**Comment by quanglam2807** [comment]
Maybe, it's related to the resizing `kernel`. lovell/sharp#621

**Comment by ianjukes** [comment]
It looks to me like the issue is when Electron creates a ICNS file for the app from the PNG? From the PNG it creates 6 different sized icons inside the one ICNS file and the 5 smaller icons are very poor quality. This might be the resizing code that Electron uses?

**Comment by quanglam2807** [comment]
Difference between None, Linear, Cubic and Sinc(Lanczos3) interpolation in image scaling?
https://graphicdesign.stackexchange.com/a/28034

**Comment by quanglam2807** [comment]
The icons are generated on the server: https://github.com/webcatalog/webcatalog-server/blob/master/src/routes/admin.js#L84 and then stored on S3.

It uses `sharp` to resize the original icons to smaller ones. But `sharp` uses `lanczos3` instead of `cubic` kernel by default. `cubic` is better at keeping edges smooth.

**Comment by ianjukes** [comment]
The code is calling a shell script that uses `png2icns` on the server https://github.com/webcatalog/webcatalog-server/blob/master/src/libs/convert-to-icns.sh to create the ICNS file from the PNG. I think this is where the problem is.

**Comment by ianjukes** [comment]
Actually, it looks like it uses `convert` from ImageMagick to resize the PNGs and then `png2icns` to combine them into an ICNS file.

**Comment by quanglam2807** [comment]
My bad. Just got it too

**Comment by ianjukes** [comment]
I think I've found the problem. In the `convert-to-icns.sh` script the ImageMagick `convert` command uses the `-sample` option to resize the images. According to the ImageMagick website https://www.imagemagick.org/script/command-line-options.php#sample that uses nearest neighbour resampling for speed, and that is unlikely to produce quality icons. I think we need to edit the `convert-to-icns.sh` script to use `-resize` and `-filter` instead of `-sample`?

**Comment by quanglam2807** [comment]
@ianjukes I copied the code from https://github.com/jiahaog/nativefier/blob/master/bin/convertToIcns so I'm not really sure. The original script uses Apple's `iconutil` but I use open-source `png2icns`

**Comment by ianjukes** [comment]
I think the code will work. We just need to tweak the options on the ImageMagick `convert` command to downsample the PNG correctly.

**Comment by quanglam2807** [comment]
@ianjukes This is an ICNS file generated using the original script (convert + iconutil). Can you test it? If it's still blurry, we would be sure that this bug is caused by `convert` code, not `png2icns`).

https://send.firefox.com/download/6a9e5edaab/#20kBrG0LyWkEcKIUO7Gidg

**Comment by quanglam2807** [comment]
It'd be awesome if you can make a PR :)

**Comment by ianjukes** [comment]
Yep. It's still not right. The resized icons are still jagged. So the problem is with `convert` and not with `png2icns`. What do you mean by a PR? Sorry for my ignorance! :)

**Comment by quanglam2807** [comment]
@ianjukes Pull Request :)

**Comment by quanglam2807** [comment]
https://send.firefox.com/download/d7fce5088c/#eFXytJOheySSBMfECIVrYw

I replaced 
```
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 16x16 "${ICONSET}/icon_16x16.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 32x32 "${ICONSET}/icon_16x16@2x.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 32x32 "${ICONSET}/icon_32x32.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 64x64 "${ICONSET}/icon_32x32@2x.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 128x128 "${ICONSET}/icon_128x128.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 256x256 "${ICONSET}/icon_128x128@2x.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 256x256 "${ICONSET}/icon_256x256.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 512x512 "${ICONSET}/icon_256x256@2x.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 512x512 "${ICONSET}/icon_512x512.png"
convert "${PNG_PATH}" -define png:big-depth=16 -define png:color-type=6 -sample 1024x1024 "${ICONSET}/icon_512x512@2x.png"
```

with
```
convert "${PNG_PATH}" -resize 16x16 "${ICONSET}/icon_16x16.png"
convert "${PNG_PATH}" -resize 32x32 "${ICONSET}/icon_16x16@2x.png"
convert "${PNG_PATH}" -resize 32x32 "${ICONSET}/icon_32x32.png"
convert "${PNG_PATH}" -resize 64x64 "${ICONSET}/icon_32x32@2x.png"
convert "${PNG_PATH}" -resize 128x128 "${ICONSET}/icon_128x128.png"
convert "${PNG_PATH}" -resize 256x256 "${ICONSET}/icon_128x128@2x.png"
convert "${PNG_PATH}" -resize 256x256 "${ICONSET}/icon_256x256.png"
convert "${PNG_PATH}" -resize 512x512 "${ICONSET}/icon_256x256@2x.png"
convert "${PNG_PATH}" -resize 512x512 "${ICONSET}/icon_512x512.png"
convert "${PNG_PATH}" -resize 1024x1024 "${ICONSET}/icon_512x512@2x.png"
```

The quality seems improved. Can you test it one more time?

**Comment by ianjukes** [comment]
Yes! That seems much better. Let's give that a go.

**Comment by ianjukes** [comment]
Can you add `-filter Lanczos` to the `convert` command and upload a test ICNS file for me to test?

**Comment by quanglam2807** [comment]
@ianjukes: https://send.firefox.com/download/de25d49dd6/#GEFyHMgFXiQs1OZUhQtYhA 
Original code: 52kb
Resize: 71kb
Resize + Lanczos: 82kb

**Comment by ianjukes** [comment]
I confirm the icons do resize much better and they look better _without_ the `-filter Lanczon` option. Your updated code looks good! I think we've solved it!

**Comment by quanglam2807** [comment]
@ianjukes Awesome! Let's close this issue.

**Comment by ianjukes** [comment]
Some of the icons just need rebuilding now. 500px hasn't been updated to the new version I sent over? If you rebuild them all you might find the upscaling from the other icons is also improved.

![screenshot](https://user-images.githubusercontent.com/6738441/32791412-e1193e48-c958-11e7-9804-738af3d31fe7.png)
