### ISSUE TITLE
App Review Guidelines

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#202]
@demicon @cotfas @ianjukes I think we need to discuss about the app review guidelines:
- What kinds of apps do you approve? 
- Icon requirements.

etc.

**Comment by demicon** [comment]
@quanglam2807 twitter seems to be the only easy source for icons. Also I tried submitting high resolution icons (1000px above), but it throws a 500 error.

**Comment by demicon** [comment]
my suggestions for approving an app:
- Only web based applications allowed
- The url should display a page which has access to login/signup page of webapp
- The urls shouldn't be a landing page for mobile apps
- The urls shouldnt be some guy's personal website, unless its a blog with reasonable content.
- No porn/spam

**Comment by quanglam2807** [comment]
@demicon Height needs to equal width. If not, you'll receive a 500

**Comment by demicon** [comment]
okay . i guess that might be the reason

**Comment by ianjukes** [comment]
I've never approved an app, only submitted apps for approval. I did create Airbnb UK... but I created that one myself in the admin console. 😎 I like the approval suggestions @demicon has put forward. They seem very sensible. It would be good to try for all icons at 1024x1024px, especially for the most popular webapps. I can recreate many of them with my design tools if there isn't one already.

**Comment by vlad-cotfas** [comment]
@demicon suggestion sounds good

**Comment by quanglam2807** [comment]
Awesome! Also, please make sure a URL starts with `http://` or `https://`. The AdminCp doesn't check for this. I'm working on a fix.

**Comment by demicon** [comment]
I think we shall try gitter.im for communication. It also has mobile apps. What do u guys suggest?

**Comment by quanglam2807** [comment]
@demicon @ianjukes @cotfas What do you think about #212? Some apps are installed by thousands of people. Some are never installed. Should we only keep a small number of popular apps?

**Comment by vlad-cotfas** [comment]
Quang, I saw the new update, I like the idea, in my opinion when we migrate to version 8, is it possible to have all apps transfered there? Because for example I`m using like ~20-40 Apps and some of them are not that popular but are usefull for me. I think it is better to have also the old Apps when we migrate to 8. :)

**Comment by demicon** [comment]
Hey @quanglam2807  The idea is good. We can have a little set of popular apps and if people start to request new apps, we can create some kind of voting poll to add most voted app. And I would also add @cotfas point here, the facility to retain currently installed app to the new version.

**Comment by quanglam2807** [comment]
@demicon @cotfas Thanks a lot for the opinions. I have created a new repo for apps: https://github.com/webcatalog/webcatalog-apps. I don't think it's necessary to only accept very popular apps but at least, we should control the quality of the submitted apps.

Also, I don't really want to move everything to the new system. The new one is incompatible with the  old and we need to slowly migrate.

**Comment by demicon** [comment]
So, only the original developer or people representing the company should submit their own app?

**Comment by quanglam2807** [comment]
@demicon Did I mention that anywhere in the documents? The project was based on `https://github.com/electron/electron-apps` so we need to modify some points. It's unlikely that Google or Facebook would submit their apps so let's be wild :)

**Comment by demicon** [comment]
I would have misread, " Must not be a copy of another company's or application's icon (see submission guidelines below" I thought it as you can put up ur logo if u r the app dev
