### ISSUE TITLE
How to view "My Apps"

### ISSUE THREAD

**Issue by dinosw** [quanglam2807/appifier#203]
Hi

How can I view a list of "my apps", or is that not possible?  
I can view a list of installed apps, but I am fairly certain that I at some point saw a button called "My Apps". If it is not currently possible, then I would really like it, if it could be implemented, as I use WebCatalog on more than one computer, so being able to view "My Apps", would be extremely useful.
I really like WebCatalog, it's a great idea, and something I have wished for, for a long time (_ever since I started using "Hermit: Lite Apps Browser" on Android_)

**Comment by quanglam2807** [comment]
I've temporarily removed the page. It'll be back soon.

**Comment by quanglam2807** [comment]
Because #212, this feature will be removed. I'm sorry.
