### ISSUE TITLE
Add tabs

### ISSUE THREAD

**Issue by roNn23** [quanglam2807/appifier#204]
In Jira, I want to open multiple Stories at once. Because of this, it would be awesome to have tabs. Currently ctrl-clicked links open in my default browser.

**Comment by mr-mmmmore** [comment]
I love appifier, the interface is slick and the web apps run really fast! I love too the fact that each app runs in its own container so cookies and other local data is not shared between apps.

The only thing that I'm missing a lot compared to Fluid App is tabs! This is really missing for productivity, I for example have a Trello app where I keep my main boards open at the same time in different tabs, this saves a lot of time! I have migrated some of my Fluid apps to Appifier and would love to do it for all of them, but the lack of tabs is too important.

It would be great if you could add tabs to Appifier!
