### ISSUE TITLE
BUG: can't uninstall Pinterest

### ISSUE THREAD

**Issue by urfausto** [quanglam2807/appifier#205]
what the hell this damn bug is: "We're sorry. WebCatalog has failed to uninstall Pinterest. CLOSE" message over and over again

windows 7 x64bit
the icon disappeared from dekstop yet the app is still there.

![buggg](https://user-images.githubusercontent.com/31393590/33093146-7047b0ba-cefc-11e7-9ae9-cf6a459a9e66.jpg)

**Comment by demicon** [comment]
@urfausto go to task manager and stop all instances of the pinterest app and then try uninstalling

**Comment by urfausto** [comment]
resolved, when i started the computer today i was able to unistall.

**Comment by quanglam2807** [comment]
@urfausto Thanks a lot for the follow-up. I think this is related to #206. Let's move there.
