### ISSUE TITLE
Linux build doesn't work properly

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#21]
Maybe because of AppImage.

**Comment by quanglam2807** [comment]
Update: .deb works perfectly on Ubuntu.

**Comment by rycon** [comment]
I had to rename the WebCatalog-2.7.2.pacman to WebCatalog-2.7.2.pkg.tar.gz, and then run sudo pacman -U WebCatalog-2.7.2.pkg.tar.gz in terminal to install.

**Comment by rycon** [comment]
Is it possible to add a .desktop after installing an app?  This way I can see and search for installed apps in the linux app launcher?

Actually it looks like it already does!  Please ignore!
