### ISSUE TITLE
WebCatalog forgets about all my installed apps after upgrading

### ISSUE THREAD

**Issue by ecbrodie** [quanglam2807/appifier#211]
## Description

When I upgrade to the latest version of WebCatalog, the app will forget about all the web apps that I had already installed via WebCatalog. Although these apps will still be installed on my computer, WebCatalog will know nothing about it and thus I need to do a reinstall via WebCatalog to keep things in-sync again.

For example, I installed Facebook Messenger on a previous WebCatalog version. I can access Messenger through WebCatalog or directly via Mac (Spotlight, Alfred, double-click on the `.app` file). After I upgrade WebCatalog, I still can access Messenger directly, but WebCatalog will think that Messenger is not installed and thus have an Install link instead of an Open link.

This isn't a big pain if I am using WebCatalog for just one web app, but this can become quite annoying and cumbersome for a WebCatalog user that installs upwards of dozens of web apps. I have reproduced this on two different Mac machines.

## Affected Versions

**WebCatalog:** 7.6.1
**OS:** MacOS 10.12.6

**Comment by quanglam2807** [comment]
I'm migrating to WebCatalog 8 #212. Hopefully, this bug will be fixed with new version.
