### ISSUE TITLE
Codenvy integration (default home page)

### ISSUE THREAD

**Issue by beevelop** [quanglam2807/appifier#217]
The Codency integration uses `codenvy.com` as default home page. When launching Webcatalog's Codenvy, this always leads to their information website. You can also link directly to https://codenvy.io/. This does not only look a lot better (you'll get their fancy loading animation right on launch), but takes you right into your Codenvy Dashboard by default.

This does also work seamlessly when you are not signed in. You will be greeted right away by their authentication form.

**Comment by quanglam2807** [comment]
@beevelop I'm migrating the directory to https://github.com/webcatalog/webcatalog-apps but because the Codenvy icon doesn't satisfy the resolution requirement, it has been removed. Do you have high-resolution icon?

**Comment by beevelop** [comment]
@quanglam2807 I reached out to the Codenvy marketing team. Let's see if they have something to offer.

**Comment by beevelop** [comment]
Bard Micklea provided me the following logo: ![logo-codenvy-white](https://user-images.githubusercontent.com/6891349/33526567-c8fc8a64-d843-11e7-87c7-848064dd92a7.png)

Is this of any use for you?

**Comment by quanglam2807** [comment]
@beevelop Thanks a lot! But can you ask him for an app icon? 1024x1024px. Precisely, a Mac icon :) I can make an icon with that PNG but it won't look good.

**Comment by beevelop** [comment]
@quanglam2807 Let's see what else they have to offer. Using clearbit I at least get a 512x512 logo: https://logo-core.clearbit.com/codenvy.com?size=512

Alternative: Get into your designer persona and make something that looks quite similar (this is not an official logo and we should definitely check back with Codenvy / Redhat if it's cool with them): 
![codenvy](https://user-images.githubusercontent.com/6891349/33526983-1a64649e-d849-11e7-82a6-3befb2d47494.jpg)

**Comment by quanglam2807** [comment]
Nice! Should we settle with this one?

![33526983-1a64649e-d849-11e7-82a6-3befb2d47494](https://user-images.githubusercontent.com/1548835/33527026-0e9ceafe-d87c-11e7-8552-2dc6abe0ee48.png)

The one on clearbit is only 300x300.

**Comment by beevelop** [comment]
@quanglam2807 Looks good. I'll give them a heads up, just to make sure it's cool with them, ok?

**Comment by quanglam2807** [comment]
@beevelop Sure!
