### ISSUE TITLE
Publish as AppImage

### ISSUE THREAD

**Issue by probonopd** [quanglam2807/appifier#219]
Please add the ability to publish the generated application as an [AppImage](https://appimage.org/).
There are tools to make this easy:

- `appimagetool` from https://github.com/AppImage/AppImageKit/
- https://www.npmjs.com/package/grunt-appimage
- https://www.npmjs.com/package/electron-builder

**Comment by probonopd** [comment]
Why was this closed? Unlike downloads for Mac and Windows, an AppImage for Linux is still missing from the GitHub Releases page. Thanks for your consideration.

**Comment by quanglam2807** [comment]
@probonopd I'm pivoting the product. I'll use AppImage soon.
