### ISSUE TITLE
Add background support

### ISSUE THREAD

**Issue by Rediwed** [quanglam2807/appifier#22]
Add support for keeping instances alive whilst window is closed (but application running). So e.g. you can close a spotify window without stopping the music from playing. Then clicking the dock icon should restore the window to it's previous instance.

**Comment by quanglam2807** [comment]
@Rediwed This could be added easily, but should we turn it on by default or not? (To save battery).

**Comment by Rediwed** [comment]
Hmmm, that's a good question. Normally I'd say yes, add it as the default option (as it is default in MacOS). But it isn't default in Windows. SO I'd say make it default in macOS but not in Windows?
