### ISSUE TITLE
"This app is no longer supported" post 8.0.3 upgrade

### ISSUE THREAD

**Issue by jefftriplett** [quanglam2807/appifier#223]
I upgraded to 8.0.3 and upon restarting all of my installed apps show "This app is no longer supported". 

![webcatalog](https://user-images.githubusercontent.com/50527/33511664-6f7e9622-d6e4-11e7-9585-5e39abdf9df0.png)

**Comment by quanglam2807** [comment]
@jefftriplett Please uninstall the apps and reinstall them. WebCatalog 8 has some major changes.

It was my mistake not to make it clearer. I'm sorry.

**Comment by quanglam2807** [comment]
I've updated the RELEASE_NOTES.md https://github.com/webcatalog/webcatalog/blob/master/RELEASE_NOTES.md. I could have done much better but it's too late :(

**Comment by jefftriplett** [comment]
No worries. I just wanted to point it out since others would see it too.
