### ISSUE TITLE
add arch linux unofficial user repository

### ISSUE THREAD

**Issue by alfinbi** [quanglam2807/appifier#225]
please add arch linux unofficial user repository so that users can easily update webcatalog using pacman -Syu. it will be a great benefit for webcatalog users to have the rolling release of webcatalog.

refer to this link

[arch linux user repo](https://wiki.archlinux.org/index.php/unofficial_user_repositories#Adding_your_repository_to_this_page)

**Comment by quanglam2807** [comment]
The app relies on `electron-builder` but the library doesn't support PPA. :( electron-userland/electron-builder#1170

**Comment by quanglam2807** [comment]
Let's move the discussion to #222
