### ISSUE TITLE
DMG image not recognized

### ISSUE THREAD

**Issue by necroshadow0** [quanglam2807/appifier#229]
I downloaded the dmg on mac osx 10.10, and It can't open
It said : " image not recognized"
what do I do?

**Comment by quanglam2807** [comment]
@necroshadow0 Maybe, the downloaded file is corrupt. Can you re-download it and try again?

**Comment by necroshadow0** [comment]
I can’t I tried it from you website, getwebcatalog.io
is it the right one?


On 6 Dec 2017 at 7:22 PM, Quang Lam <notifications@github.com> wrote:


@necroshadow0 <https://github.com/necroshadow0> Maybe, the downloaded file
is corrupt. Can you re-download it and try again?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/webcatalog/webcatalog/issues/229#issuecomment-349610660>,
or mute the thread

**Comment by quanglam2807** [comment]
@necroshadow0 Accurately, https://webcatalog.io :)

**Comment by necroshadow0** [comment]
maybe it’s because I use sierra….


On 7 Dec 2017 at 6:08 PM, Quang Lam <notifications@github.com> wrote:


@necroshadow0 <https://github.com/necroshadow0> Accurately,
https://webcatalog.io

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/webcatalog/webcatalog/issues/229#issuecomment-349921708>,
or mute the thread

**Comment by quanglam2807** [comment]
@necroshadow0 I'm sorry that the file doesn't work on your machine. WebCatalog is supported to work on Sierra so it's not your fault. Can you try to install with the ZIP installer: https://github.com/webcatalog/webcatalog/releases/download/v8.0.5/WebCatalog-8.0.5-mac.zip
