### ISSUE TITLE
Opening a File in OneDrive Opens a _Blank Window With No Contents

### ISSUE THREAD

**Issue by rycon** [quanglam2807/appifier#23]
(I'm using the new Linux Version on Arch Linux

After installing and logging into my onedrive account, when I select a document to view, a new _blank window is open and has no contents, just a white screen.

![onedrive](https://cloud.githubusercontent.com/assets/8238505/21982562/25dc8230-dbaa-11e6-815a-7147ad0be6a5.png)
)

**Comment by Rediwed** [comment]
I've seen the same result when trying to add a google account in the macOS version. Might be related?
https://www.reddit.com/r/apple/comments/5mth5g/webcatalog_for_macos_run_your_favorite_web_apps/dcbrr8q/
