### ISSUE TITLE
Icon distortion

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#230]
```
Jon Nelson

Hi. Thanks again and great work on your continued development and the new version.

One kind of "big" issue I'm having, after uninstalling and reinstalling apps (from library OR custom): The app icon appears distorted in my taskbar/desktop dockbar  (please see screenshots)
I am using a custom dockbar (Winstep) and I have never had this issue before. There is something in the way that the new webcatalog creates/saves the icon that appears funny. Only if I use Rescource Hacker to replace the icon of the webcatalog app with another .ico file, does the app icon appear properly...

*This happens with the icons for apps from the catalog, as well as custom icons which I add for custom apps.
```

![capture 2](https://user-images.githubusercontent.com/1548835/33802739-a5a13e76-ddb0-11e7-97ee-095ce19b14da.PNG)
![capture](https://user-images.githubusercontent.com/1548835/33802740-a5de0306-ddb0-11e7-82bd-c7dd5e69a82e.PNG)

**Comment by jonsnelson** [comment]
Thanks for trying to solve this. How are you able to reproduce the issue? Are you using a custom dock bar? (So far, I don't notice the issue on my native windows dock/task bar, only on my Winstep taskbar...)
Anyway, I'd be happy to try things out for you if you need someone to test things :)
Thanks!

**Comment by quanglam2807** [comment]
@jonsnelson Thanks a lot! I need to issue a few releases to see what library works best.

I have tried https://github.com/akabekobeko/npm-icon-gen & https://github.com/kevva/to-ico but they don't seem to work correctly.

The only hope we have now is https://github.com/steambap/png-to-ico. 

The libraries are Javascript-based while the one I used in WebCatalog 7 was a native one (imagemagick) but it's quite cumbersome to use it in the WebCatalog 8 due to technical changes.

**Comment by jonsnelson** [comment]
thanks for trying. hopefully it will work out !

**Comment by quanglam2807** [comment]
@akabekobeko Can you help with this, please?

**Comment by quanglam2807** [comment]
As I tested, `icon-gen` & `to-ico` generate identical files while `png-to-ico` generates smaller file. 

<img width="695" alt="screen shot 2017-12-18 at 1 07 43 pm" src="https://user-images.githubusercontent.com/1548835/34092143-941cdcc4-e3f4-11e7-8c1d-75b67bd3b68b.png">

**Comment by akabekobeko** [comment]
@quanglam2807 

Because using [Winstep Nexus Dock](http://www.winstep.net/nexus.asp), it seems to be Windows and `ICO` file problem.

Win32 API is not used for `ICO` file generation processing by `icon-gen`, Building [BITMAPINFOHEADER](https://msdn.microsoft.com/ja-jp/library/windows/desktop/dd183376(v=vs.85).aspx) independently, but the `BITMAP` part is uncompressed (BGRA/Bottom-Left).

It seems that `BITMAP` may not be compressed as `ICO`, But depending on the application it may be problem.

**Comment by quanglam2807** [comment]
@akabekobeko Thanks a lot for clarifying. I don't understand what you mean clearly but I guess the file generated by `png-to-ico` is smaller than the one generated by `icon-gen` because the former compresses the `BITMAP` part, right?

@jonsnelson please test these `ICO` files to see if any of them works with Winstep. https://we.tl/sZ2vSjqZhP.

**Comment by jonsnelson** [comment]
In my test all three of those work great in Winstep!  (Note: *"png-to-ico" has less sizes though). 

However, I can't say for sure until I try an actual app created with that ico resource file. 

Just to clarify how I tested: Using Resource Hacker I opened the apps's .exe file (I tested on webcatalog's ebay app) and: 
1) saved the original .ico resource to another folder.
2) replaced the .ico with your new ones and tasted (all looked fine)
3) tried again with the original saved .ico resource (looked distorted!)

**Comment by quanglam2807** [comment]
@jonsnelson This is strange. Can you upload the original .ico resource?

**Comment by jonsnelson** [comment]
[ebay.zip](https://github.com/webcatalog/webcatalog/files/1571559/ebay.zip)
Sure (uploaded):
To clarify: In order to compare I tried the _new_ .ico files you sent (which looked fine) and THEN the original one (which looked distorted) I wanted to be sure that that the new ones worked because of the .ico files __themselves__ and NOT because of something that Resource Hacker did to the .ico  file when it replaced it.

**Comment by jonsnelson** [comment]
Is there anyway for you to send an actual webcatalog app  (using one of the new .ico)?
Then I could be 100% sure that it works...

**Comment by quanglam2807** [comment]
@jonsnelson It is odd that I can't even open the `.ico` file on my Mac. And actually, I don't think it is necessary to send the whole app as I won't be able to extract any valuable information from it. I'll allow creating custom apps with `.ico` file in the upcoming versions so you can generate the icons with different software.

**Comment by jonsnelson** [comment]
I'm confused. Are you going to package the non-custom apps (also) - such as Gmail, Maps, etc...- with a new kind of .ico file? (not just letting me do that for custom apps) 

As it is now, I can use Resource to re-package your apps with .ico which work fine with winstep. I was hoping that you would use an .ico resource which works for me "out of the box"  :)

Eitherway ,thanks as always for your time and work!

**Comment by quanglam2807** [comment]
@jonsnelson Well, you can definitely create a custom Gmail, Maps app, etc. But it is strange that if you use Resource to re-package the apps with the `.ico` files I sent you, they work fine with Winstep. Because if so, the problem is not caused by the icon files but by something else.

I'm not sure if I can find a optimal solution soon but I'm working to open-source the project more and more. So hopefully, somebody would jump in and solve this.

Again, I'm really appreciated and sorry for not being able to fix this.

**Comment by jonsnelson** [comment]
I am confused, and maybe you misunderstood me.

**Comment by quanglam2807** [comment]
@jonsnelson Basically, the next update won't fix this issue :) Let's wait for somebody to fix it :)

**Comment by jonsnelson** [comment]
I am confused, and maybe you misunderstood me. 
1- The  .ico files you sent me worked great (with winstep) when I used Resource to package them into the apps. 
2- The ORIGINAL .ico file which came with the app from the WebCatalog directory DOESN'T work (with winstep): doesn't work "out of the box" AND doesn't work EVEN IF repackaged with Resource.

Doesn't that show that there is a problem with the ORIGINAL .ico file you packaged the the apps with?

I wanted you to package some app with one of the new icon files, and if you send it to me I could be sure.

**Comment by quanglam2807** [comment]
@jonsnelson Actually, where did you find the `ORIGINAL .ico`?

**Comment by jonsnelson** [comment]
I simply mean the .ico which came with the WebCatalog apps from the directory. 
1) Using Rescource, I opened the .exe app (of Ebay for example) and used the "save .ico resource" function. That way I had a backup of it. 
2) Then I REPLACED that original .ico resource with your new one, and it worked great! 
3) Then, to test, I put BACK the original (backed up) .ico that came with app, and it didn't work,
Is that clear?

**Comment by quanglam2807** [comment]
@jonsnelson Thanks a lot. I got it! So:

```
1. The .ico files you sent me worked great (with winstep) when I used Resource to package them into the apps.
2. The ORIGINAL .ico file which came with the app from the WebCatalog directory DOESN'T work (with winstep): doesn't work "out of the box" AND doesn't work EVEN IF repackaged with Resource.

Doesn't that show that there is a problem with the ORIGINAL .ico file you packaged the the apps with?
```

The problem is that the icons I sent you and the icons you extracted from the .exe are generated by the same libraries. So I still don't know what causes the issue.

**Comment by jonsnelson** [comment]
So what was the difference between those icons and the original ones? I thought you were testing something new?

**Comment by quanglam2807** [comment]
@jonsnelson I sent you 3 `.ico` files: `to-ico.ico`, `icon-gen.ico`, `png-to-ico.ico`. Their names are the names of 3 different icon-converting libraries I'm testing.

https://github.com/akabekobeko/npm-icon-gen
https://github.com/kevva/to-ico
https://github.com/steambap/png-to-ico

The one WebCatalog is currently using is `npm-icon-gen`. So I would expect `icon-gen.ico` and the `.ico` extracted from `.exe` to work identically. But as you tested, they're not.

**Comment by jonsnelson** [comment]
So---doesn't that mean that if you use one of those 3 libraries it might help?
Maybe you could try packaging an app with one of those libraries and send me to test?

**Comment by quanglam2807** [comment]
@jonsnelson Sure. I'll try do that soon.

**Comment by jonsnelson** [comment]
I just updated to the new Webcatalog (9.2.1) and updated a few apps and the icons seem to be good in Winstep. 
Fixed?!
👍

**Comment by quanglam2807** [comment]
@jonsnelson I didn't change anything but maybe, it's thanks to @VirgileACM's quanglam2807/webcatalog-apps#13
