### ISSUE TITLE
Multiple windows/Tabs

### ISSUE THREAD

**Issue by brossi17** [quanglam2807/appifier#233]
I love the experience of running my favorite websites as full screen apps, but one major limiting feature is the inability to run multiple tabs/windows on the same website, which I often do on web browsers and often prevents me from using webcatalog. I would love to see this feature implemented.

**Comment by quanglam2807** [comment]
Thanks a lot for the feedback. I'll try to work on this. But it's not my priority at the moment. Let's move the discussion to #204

**Comment by pafffkata** [comment]
@quanglam2807 are you planning on implementing something like that in the long run at all?
I have the same use case - I like using the app, but at some point in time I need to open a couple of tabs on the same web page, just different sections.

Not being able to do this in WebCatalog is really a like @brossi17 said "a limiting feature".

**Comment by quanglam2807** [comment]
@pafffkata We should move to #204. Anyway, I'd love to build this feature but it would require changing the structure of the app (to support multiple web views). Right now, it's possible but it would mean running many web views at the same time which Electron is not optimized for.
