### ISSUE TITLE
Apps not working after installing High Sierra

### ISSUE THREAD

**Issue by emailalinda** [quanglam2807/appifier#234]
Hi! 
I just installed High Sierra for mac this morning and now many of the apps are not working - Google Calendar, Netflix, Google Play music and Google Analytics seem to have gotten uninstalled and when I try to reinstall it says that an error occurred... what to do? Thanks!

**Comment by quanglam2807** [comment]
I'm sorry for the issue. I'm working to fix it ASAP. Let's move the discussion to #221
