### ISSUE TITLE
Misuse of ~/.config folder for storing binary files of installed web apps in linux

### ISSUE THREAD

**Issue by dbadaya1** [quanglam2807/appifier#235]
I noticed binaries for installed webapps are stored in ~/.config/WebCatalog/apps
This increases the size of ~/.config folder significantly, making it less practical to sync this folder across devices.
Can we move the this folder to somplace else ? Maybe /opt/WebCatalog/apps ?

**Comment by jlandes** [comment]
I'm in agreement on this one.

**Comment by quanglam2807** [comment]
It won't be hard to accomplish this but backward compatibility would be a problem.

**Comment by jlandes** [comment]
@quanglam2807 I think it'd be easy enough to write a script to move the data from ~/.config/WebCatalog/apps to /opt/WebCatalog/apps and that script should only need to be run once. Or, possibly make it part of the install for new versions that it checks for apps in the ~/.config/WebCatalog/apps and moves them over. Maybe you have some better ideas.

**Comment by quanglam2807** [comment]
@jlandes  It would mean I need to add and maintain some code. When the folder is moved, the shortcut files also need to be updated.

**Comment by quanglam2807** [comment]
@jlandes @dbadaya1  I would make an update with breaking changes. `/opt` is much better choice.

https://unix.stackexchange.com/questions/11544/what-is-the-difference-between-opt-and-usr-local

**Comment by dbadaya1** [comment]
After thinking about this for a while, I think /opt would not be a good choice.
Reasons being
- /opt is writable only by root. Webcatalog must be run as root to install apps. Users without sudo permission would not be unable to install webapps

-  /opt is shared by all users. So, if a user installs an app, it will automatically be installed for all users. I don't think this is the desired behaviour.

IMO we should instead move apps to ~/.local

**Comment by quanglam2807** [comment]
@dbadaya1 Right now, there's a folder at `~/.webcatalog`. Should we use it instead?

**Comment by dbadaya1** [comment]
~/.webcatalog is fine with me.

**Comment by quanglam2807** [comment]
I've cut the release with this change.

If you guys can, please test https://github.com/webcatalog/webcatalog/releases/tag/v9.0.0 and let me it works correctly.

**Comment by leogallego** [comment]
Hello, sorry to reopen this, but, I think you should stick to XDG Base Directory Specifications. This is compliant with almost every Linux desktop. Using the old "~/.webcatalog" is discontinued and shouldn't be used (at least if you care about this things and compatibility across multiple distributions).

**.config/webcatalog** for the app configuration
**.local/share/webcatalog** for the app data.

More info:
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by quanglam2807** [comment]
@hombrepac I don't use Linux as my daily driver so it's hard for me to make a good decision for this issue. I would like to read more opinions from other people.
