### ISSUE TITLE
Request: Multi-language spelling

### ISSUE THREAD

**Issue by poxtron** [quanglam2807/appifier#236]
Hello, this is a very useful tool only one thing missing: spelling check with different languages. 

If you can accomplish this then it would be perfect.

Thanks.

**Comment by quanglam2807** [comment]
It's supposed to detect language automatically but there's a bug (electron-userland/electron-spellchecker#85). 

It's possible to add an option to set the language manually but I don't know where to find the list of the supported languages.

**Comment by christian-putzke** [comment]
It would be really great to set the language for the spell checking manually. Under Windows 10 the spell checking for all web catalog apps is using English for me even if I have a German operating system.
