### ISSUE TITLE
Apps are stuck on installation

### ISSUE THREAD

**Issue by bansalsohil** [quanglam2807/appifier#237]

**Comment by quanglam2807** [comment]
@bansalsohil I'm sorry for the issue. Which OS are you using?

**Comment by bansalsohil** [comment]
@quanglam2807 sorry it happened because I opened the app through .dmg and after I quit there was still some background session running. The issue got resolved after restarting the system.

**Comment by quanglam2807** [comment]
@bansalsohil I'm glad to know that! Thanks a lot.
