### ISSUE TITLE
Portable Appdata

### ISSUE THREAD

**Issue by areebqaisar** [quanglam2807/appifier#239]
The Default Application Data of the Created App, is saved in the User's Profile Directory.
In case of Windows it is:
C:\Users\username\AppData\Roaming\CreatedAppName

Is there anyway, we can use the Created App as PortableApp ? Or any method by which we can customize the Default Location of AppData ?

**Comment by quanglam2807** [comment]
@areebqaisar You can probably use the CLI :)

**Comment by areebqaisar** [comment]
Thanks. Can you please guide me how to use the CLI ? Like the parameters for npm etc ?

**Comment by quanglam2807** [comment]
@areebqaisar Here is it: https://github.com/quanglam2807/webcatalog#command-line

**Comment by areebqaisar** [comment]
So, in this Command, which parameter should I add to specify the Custom AppData Directory ?

appifier --id duckduckgo --name "DuckDuckGo" --url "https://duckduckgo.com" --icon ./icon.png

**Comment by quanglam2807** [comment]
—

**Comment by quanglam2807** [comment]
https://github.com/quanglam2807/webcatalog/blob/master/API.md

**Comment by quanglam2807** [comment]
@areebqaisar I'm sorry. I didn't understand what you mean correctly. I'll take a look at this soon.

**Comment by quanglam2807** [comment]
This can be resolved by:
- Adding an option for Default Application Data in the preferences page.
- Using `app.setPath` to change the path based on the preference. (https://github.com/electron/electron/blob/master/docs/api/app.md#appsetpathname-path)

It would be nice if you or someone else work on this as I don't have time to add features.
