### ISSUE TITLE
Google Calendar on Mac does not display location matches

### ISSUE THREAD

**Issue by garyhooper** [quanglam2807/appifier#242]
I have create a web catalog app for calendar.google.com on Mac. When modifying events to include a location, the calendar app lists potential locations matches (based on what I have typed in so far) in a list. This functionality is not working in the WebCatalog app.

Suggestions?

**Comment by swrobel** [comment]
Working fine for me, WebCatalog 9.1.2, macOS 10.13.2
<img width="672" alt="screen shot 2017-12-29 at 2 14 56 pm" src="https://user-images.githubusercontent.com/157270/34448492-b1387f64-eca2-11e7-801d-fb0052ef9678.png">

**Comment by garyhooper** [comment]
Bizarre.  Rebooting corrected it for me too...
