### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#249]
@nyex suggests translating the app to Portuguese (Thanks a lot!!!). The strings are already organized in 2 files: 
https://github.com/quanglam2807/webcatalog/blob/master/src/constants/strings.js
https://github.com/quanglam2807/webcatalog/blob/master/packages/appifier/app/src/constants/strings.js

But it requires some modifications like a setting to change the language, structural changes to support multiple languages. 

I don't have time to work on this at the moment. But hopefully, I or somebody can work on this soon.

**Comment by nyex** [comment]
I can easily translate all those (I can also translate to Spanish), but I have no idea about how to do it code-wise (as in how to save the file, where to add the translated string etc); I've only translated .po files for wordpress so far 😀... So I'm accepting help in that area.

**Comment by quanglam2807** [comment]
Thanks a lot! But until I resolve this issue, you won’t be able to translate the app.

**Comment by sikenali** [comment]
Chinese support
