### ISSUE TITLE
Google Keep trigger discrete graphics card

### ISSUE THREAD

**Issue by Rediwed** [quanglam2807/appifier#25]
Launching the Google Keep web app unfortunately triggers macOS to use it's discrete graphics card instead of the integrated (intel hd/Iris Pro) graphics.

**Comment by quanglam2807** [comment]
@Rediwed How can you check this?

**Comment by Rediwed** [comment]
I posted it ;)

**Comment by Rediwed** [comment]
By using gfxCardstatus! 

But you need a fork from the official version for macOS Sierra, I'll post a link soon.

**Comment by Rediwed** [comment]
Try this fork of Gfxcardstatus:  https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

**Comment by quanglam2807** [comment]
@Rediwed Can you try again with the lastest update? Maybe the new version of Chrome has fixed the problem.

**Comment by Rediwed** [comment]
Sadly, it still triggers the discrete graphics card :(

**Comment by quanglam2807** [comment]
@Rediwed It seems like I've found the problem: https://developer.apple.com/library/content/qa/qa1734/_index.html

Beta is coming :)

**Comment by Rediwed** [comment]
Great to hear!!!

**Comment by quanglam2807** [comment]
@Rediwed It's up now. Please try :)

**Comment by quanglam2807** [comment]
@Rediwed The "fix" has been there since the beginning. So it won't fix the issue :(.

**Comment by Rediwed** [comment]
Hmm, that's too bad. Maybe there's a way to force an application to use the integrated gfx card? I know gfxcardstatus actually has this ability.

**Comment by quanglam2807** [comment]
@Rediwed Haha, maybe I was right but I did configure the code incorrectly. You can try again with 3.2.1 (beta). After installing the update, opening WebCatalog first so it can update all the apps (including Google Keep) automatically. Then you can try again 👍 . Hope it works.

**Comment by quanglam2807** [comment]
@Rediwed Please try https://github.com/webcatalog/desktop/releases/tag/v3.2.5. I'll reopen the issue if it still doesn't work properly.

**Comment by Rediwed** [comment]
I tried 3.2.5, sadly it still triggered the discrete gfxcard..

**Comment by quanglam2807** [comment]
Can you upload the Info.plist at `~/Applications/WebCatalog Apps/Google Keep.app/Info.plist`?
