### ISSUE TITLE
Unable to update or install previously installed apps since 9.2.1 update.

### ISSUE THREAD

**Issue by CodeBrotha** [quanglam2807/appifier#251]
Ubuntu 16.04 (elementary OS Loki)
Webcatalog 9.2.1

Since updating to version 9.2.1 I am unable to update apps or install apps that were previously installed, then removed.

Attached screenshot shows the error message.

![install-error](https://user-images.githubusercontent.com/15023217/34928460-ab1d3de0-f98b-11e7-9f7e-7d49dd425ad8.png)

**Comment by quanglam2807** [comment]
Similar to #248
