### ISSUE TITLE
Asana not installing

### ISSUE THREAD

**Issue by bagarwood** [quanglam2807/appifier#253]
Just wanted to let you know that Asana will not install or update. Thanks!

**Comment by quanglam2807** [comment]
Hi! What OS are you using?

**Comment by bagarwood** [comment]
The latest release.

Thanks!
BRETT GARWOOD Freelancer

	  	
WEB & GRAPHIC DESIGNER
4003 Caln Circle, Harleysville, PA 19438
Phone: (517) 270-1770  Web: brettgarwood.com 
     
This electronic mail transmission and any accompanying attachments contain confidential information intended only for the use of the individual or entity named above. Any dissemination, distribution, copying or action taken in reliance on the contents of this communication by anyone other than the intended recipient is strictly prohibited. If you have received this communication in error please immediately delete the email and notify the sender.


On Jan 19, 2018, at 6:41 PM, Quang Lam <notifications@github.com> wrote:

Hi! What OS are you using?

**Comment by quanglam2807** [comment]
Thanks for the response. But I mean are you using Windows, macOS or Linux?

**Comment by bagarwood** [comment]
Sorry macOS. 

BRETT GARWOOD Freelancer

	  	
WEB & GRAPHIC DESIGNER
4003 Caln Circle, Harleysville, PA 19438
Phone: (517) 270-1770  Web: brettgarwood.com 
     
This electronic mail transmission and any accompanying attachments contain confidential information intended only for the use of the individual or entity named above. Any dissemination, distribution, copying or action taken in reliance on the contents of this communication by anyone other than the intended recipient is strictly prohibited. If you have received this communication in error please immediately delete the email and notify the sender.


On Jan 19, 2018, at 8:35 PM, Quang Lam <notifications@github.com> wrote:

Thanks for the response. But I mean are you using Windows, macOS or Linux?

**Comment by quanglam2807** [comment]
A new version will be available soon at: https://github.com/quanglam2807/webcatalog
