### ISSUE TITLE
MenuBar

### ISSUE THREAD

**Issue by educastro11** [quanglam2807/appifier#257]
I've got WebCatalog app for MAC. Wonderful idea!
I did install youtube in it. I Loved.
I'd like to give a suggestion. What about putting a MenuBar icon where you could access this youtube app just as an app called Muse in Mac App Store ?

**Comment by educastro11** [comment]
did you close? not a good idea?

**Comment by quanglam2807** [comment]
@educastro11 I just closed one of them. It's duplicated. Also, I've received your email. I'll try to work on this.

**Comment by educastro11** [comment]
thank you!!
