### ISSUE TITLE
Apps don't open on assigned workspace

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#26]
OSX allows to assign default workspaces for each application, by right clicking an applications icon and selecting "This desktop".
![desktopassignmentmenu](https://cloud.githubusercontent.com/assets/2744198/22026754/00b8c10c-dcd2-11e6-892d-7667ea4a8302.png)

Applications from Webcatalog always open on the current workspace, and not within a previously assigned workspace.

**Comment by quanglam2807** [comment]
@jottr WebCatalog relies on bash script so maybe I would be able to fix it there's a command to launch an app in a specific workspace. Do you have any idea?

**Comment by jottr** [comment]
Not really. I've just had a superficial glance at your project. Where exactly is the launch script?

**Comment by quanglam2807** [comment]
@jottr https://github.com/webcatalog/desktop/blob/master/app/applify-darwin.sh

**Comment by jottr** [comment]
I still have no idea how this could be achieved, but I would like to argue that this issue should be bumped in criticality.   

Since webcatalog aims to create native style applications, which behave like proper desktop applications, it should adhere to a platforms UX standards. 

What can we do to resolve this issue?

**Comment by quanglam2807** [comment]
@jottr I think the best solution is to use native binaries. Now each app installed from WebCatalog uses shortcut file (on Windows) or bash file (Mac & Linux) to trigger. Those apps will open webcatalog binary with specific parameters. Because of this, it's very limited to control the behaviors of the apps. 

So instead of using bash script, if we can compile a proper binary for every app, it would work much better. This is what Google does with Chrome apps. But I don't know much about native programming.

**Comment by jottr** [comment]
What do you think about [Gallium](https://github.com/alexflint/gallium)?

**Comment by quanglam2807** [comment]
@jottr Pretty neat but but it hasn't been updated for months. Electron is getting better and better so I don't think we need to switch anytime soon.

**Comment by quanglam2807** [comment]
@jottr I think I'll change the way WebCatalog works to fix issues similar to this one. The apps will be independent Electron apps instead of using a same binary.

**Comment by quanglam2807** [comment]
Should be fixed with #141

**Comment by jottr** [comment]
It seems that only webcatalog itself can be assigned to a workspace, but not apps installed via webcatalog. 
Tested on webcatalog 6.1.0

**Comment by quanglam2807** [comment]
@jottr Yes, I understand the problem. With the next version, 7.0, we are moving to a new architecture to resolve this issue: https://github.com/webcatalog/webcatalog/issues/148#issuecomment-312166657
