### ISSUE TITLE
icon.png  support 128*128？

### ISSUE THREAD

**Issue by sikenali** [quanglam2807/appifier#260]
I uploaded a svg  128× 128 
![_ _20180211151241](https://user-images.githubusercontent.com/26103116/36070811-1f55d20e-0f3e-11e8-9f5a-e22e3ab7e4d1.png)

**Comment by jingle0927** [comment]
![_appifier_20180211145819](https://user-images.githubusercontent.com/26103116/36070730-0db7e458-0f3c-11e8-8b92-2a723f3880dd.png)

**Comment by sikenali** [comment]
support png jpg or  svg or   others？？？？？？

**Comment by quanglam2807** [comment]
Appifier GUI has been deprecated. Please wait for the first release of https://github.com/quanglam2807/webcatalog-lite

**Comment by sikenali** [comment]
Thanks
