### ISSUE TITLE
Microsoft Teams Stuck on Initialization

### ISSUE THREAD

**Issue by rycon** [quanglam2807/appifier#28]
On the Linux version.
After installing the MS Teams app and logging in o my windows live account, the window stays  purple, and the title state "Microsoft Teams - initializing..." and nothing loads.

![ms teams](https://cloud.githubusercontent.com/assets/8238505/22062767/adb3f91a-dd38-11e6-8e9f-687d7b7869a9.png)

**Comment by rycon** [comment]
There look to be some errors in the dev console:

![dev console errors](https://cloud.githubusercontent.com/assets/8238505/22063587/cd33ba56-dd3c-11e6-9c6a-b696db710e50.png)

index.html: register for events
_:57 index.html: check for appcache update. State: 2
_:65 index.html: update not ready, continue with app start
_:1 Document was loaded from Application Cache with manifest https://teams.microsoft.com/skypespaces.appcache
_:1 Application Cache Checking event
_:1 Application Cache NoUpdate event
_:178 Loading stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.min-19666b66.css
angular.min.js:117 Error: Script error.
    at a.onerror (https://statics.teams.microsoft.com/hashedjs/3-app.min-4f9e27eb.js:1113:24607) undefined(anonymous function) @ angular.min.js:117
angular.min.js:40 Uncaught TypeError: Cannot read property 'on' of undefined
_:195 Loaded stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.min-19666b66.css
_:34 index.html: cache up-to-date
_:40 index.html: remove startup cache listeners
https://teams.microsoft.com/dist-assets/fonts/Segoe-UI/3ca1af51-981a-4e1c-b9c6-a66d0a5fe3c0-1-de0225fe.woff2?v=2 Failed to load resource: the server responded with a status of 404 (Not Found)
https://teams.microsoft.com/dist-assets/fonts/Segoe-UI/3ca1af51-981a-4e1c-b9c6-a66d0a5fe3c0-3-2e999100.woff?v=2 Failed to load resource: the server responded with a status of 404 (Not Found)
https://teams.microsoft.com/dist-assets/fonts/Segoe-UI/3ca1af51-981a-4e1c-b9c6-a66d0a5fe3c0-1-718ad08e.ttf?v=2 Failed to load resource: the server responded with a status of 404 (Not Found)
browser.js:46 Error: getaddrinfo -3008(…)(anonymous function) @ browser.js:46
browser.js:46 Error: getaddrinfo -3008(…)

**Comment by quanglam2807** [comment]
@rycon Can you also share the dev console when you access Microsoft Teams with Google Chrome? I don't have Office 365 account so I can't test this myself.

**Comment by rycon** [comment]
Here ya go
![image](https://cloud.githubusercontent.com/assets/8238505/22089364/ddb7b3ee-dda7-11e6-83cc-593da3feb56e.png)


Loading stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.min-7fe0afce.css
angular.min.js:117 2017-01-19T00:58:32.061Z Orchestrator: Could not find action registered with name: "callLogStore:startup"
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
a.registerStep @ orchestrationService.min.js:1
(anonymous) @ orchestrationService.min.js:1
(anonymous) @ orchestrationService.min.js:1
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:145
$digest @ angular.min.js:142
g.$digest @ scalyr.min.js:1
g.$digest.m.$digest @ heartbeatService.min.js:1
$apply @ angular.min.js:145
(anonymous) @ angular.min.js:21
invoke @ angular.min.js:41
c @ angular.min.js:21
yc @ angular.min.js:21
(anonymous) @ _:220
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
4angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 2017-01-19T00:58:32.136Z callingAgents: failed initializing calling agents. support: 1, error: 
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
(anonymous) @ callingAgentsService.min.js:1
_:1 Application Cache Progress event (5 of 9) https://statics.teams.microsoft.com/hashedjs/3-app.min-08882d3b.js
_:1 Application Cache Progress event (6 of 9) https://statics.teams.microsoft.com/hashedcss/stylesheets.min-7fe0afce.css
_:1 Application Cache Progress event (7 of 9) https://statics.teams.microsoft.com/hashedjs/pdf.worker-49d1619f.js
_:1 Application Cache Progress event (8 of 9) https://teams.microsoft.com/webworker-dfccc4ca.js
_:40 index.html: remove startup cache listeners
2angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
_:1 Application Cache Progress event (9 of 9) 
_:1 Application Cache Cached event
_:194 Loaded stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.min-7fe0afce.css
pageAction.js:6 Object {Black Mirror: Object, Einsatzgruppen: The Nazi Death Squads: Object, Gilmore Girls: A Year in the Life: Object, Legend: Object, Mad Men: Object…}
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 LoggingContextService: No params can be used as the key to resolve a conversation. Either this is not a conversation or different parameter should be used.
angular.min.js:117 2017-01-19T00:58:39.833Z callingService: Calling initialization failed: Error: NotSupported
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
(anonymous) @ callingService.min.js:1
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:145
$digest @ angular.min.js:142
g.$digest @ scalyr.min.js:1
g.$digest.m.$digest @ heartbeatService.min.js:1
$apply @ angular.min.js:145
(anonymous) @ angular.min.js:97
y @ angular.min.js:101
t.onload @ angular.min.js:102
angular.min.js:117 2017-01-19T00:58:39.836Z Orchestrator: calling orchestration: [object Object]
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
(anonymous) @ setupSkypeCallingOrchestrationStep.min.js:1
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:145
$digest @ angular.min.js:142
g.$digest @ scalyr.min.js:1
g.$digest.m.$digest @ heartbeatService.min.js:1
$apply @ angular.min.js:145
(anonymous) @ angular.min.js:97
y @ angular.min.js:101
t.onload @ angular.min.js:102
VM1510 XFrame.js:146 GET https://webdir.online.lync.com/ucwa/oauth 401 (Unauthorized)
sendRequest @ VM1510 XFrame.js:146
(anonymous) @ VM1510 XFrame.js:210
VM1607 XFrame.js:146 GET https://webdir1a.online.lync.com/Autodiscover/AutodiscoverService.svc/root/oauth/user 401 (Unauthorized)
sendRequest @ VM1607 XFrame.js:146
(anonymous) @ VM1607 XFrame.js:210
VM1607 XFrame.js:146 GET https://webdir1a.online.lync.com/ucwa/oauth 401 (Unauthorized)
sendRequest @ VM1607 XFrame.js:146
(anonymous) @ VM1607 XFrame.js:210
VM1941 XFrame.js:146 GET https://webdir2a.online.lync.com/Autodiscover/AutodiscoverService.svc/root/oauth/user 401 (Unauthorized)
sendRequest @ VM1941 XFrame.js:146
(anonymous) @ VM1941 XFrame.js:210
VM1941 XFrame.js:146 GET https://webdir2a.online.lync.com/ucwa/oauth 401 (Unauthorized)
sendRequest @ VM1941 XFrame.js:146
(anonymous) @ VM1941 XFrame.js:210
XFrame.js:146 POST https://webpooldm12a04.infra.lync.com/ucwa/oauth/v1/applications 401 (Unauthorized)
sendRequest @ XFrame.js:146
(anonymous) @ XFrame.js:210
XFrame.js:146 GET https://webpooldm12a04.infra.lync.com/ucwa/oauth 401 (Unauthorized)
sendRequest @ XFrame.js:146
(anonymous) @ XFrame.js:210
angular.min.js:117 2017-01-19T00:59:58.856Z VR: blank view for 1 seconds
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
(anonymous) @ virtual-repeat-2.min.js:2
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:145
$digest @ angular.min.js:142
g.$digest @ scalyr.min.js:1
g.$digest.m.$digest @ heartbeatService.min.js:1
(anonymous) @ angular.min.js:145
e @ angular.min.js:45
(anonymous) @ angular.min.js:48
angular.min.js:117 2017-01-19T01:00:00.872Z VR: blank view for 3 seconds
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
(anonymous) @ virtual-repeat-2.min.js:2
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:145
$digest @ angular.min.js:142
g.$digest @ scalyr.min.js:1
g.$digest.m.$digest @ heartbeatService.min.js:1
(anonymous) @ angular.min.js:145
e @ angular.min.js:45
(anonymous) @ angular.min.js:48
angular.min.js:117 2017-01-19T01:00:04.888Z VR: blank view for 7 seconds
(anonymous) @ angular.min.js:117
f.logMessage @ loggingService.min.js:1
a.error @ loggingService.min.js:1
(anonymous) @ virtual-repeat-2.min.js:2
(anonymous) @ angular.min.js:130
$eval @ angular.min.js:145
$digest @ angular.min.js:142
g.$digest @ scalyr.min.js:1
g.$digest.m.$digest @ heartbeatService.min.js:1
(anonymous) @ angular.min.js:145
e @ angular.min.js:45
(anonymous) @ angular.min.js:48
XFrame.js:146 GET https://webpooldm12a04.infra.lync.com/ucwa/oauth/v1/applications/1118203821…-111820382196-NWQwM2QyZTYtMGIyZS00OWJhLWI0NWYtZjM5NjM3YTU0N2Iy&timeout=180 net::ERR_EMPTY_RESPONSE

**Comment by quanglam2807** [comment]
@rycon I guest it's because Microsoft also uses Electron to build their desktop app so the website thinks WebCatalog is the app from Microsoft and tries to use some special components and causes the issues. I would try to change the user-agent of WebCatalog to see if it fixes the problem.

**Comment by rycon** [comment]
cool thanks man!

**Comment by quanglam2807** [comment]
@rycon What about #29?

**Comment by rycon** [comment]
I'm on my windows machine right now and the installed view works.  I'll login to linux in a bit and update that bug.

**Comment by quanglam2807** [comment]
@rycon Update is up now! Give it a try :)

**Comment by rycon** [comment]
It works now!
