### ISSUE TITLE
Nothing Listed in Installed View

### ISSUE THREAD

**Issue by rycon** [quanglam2807/appifier#29]
Linux version.
After installing a few apps, when I switch over to the installed view, I don't see any of my installed app.

For example, I have MS Teams, Onedrive, and Whatsapp installed.

![installed app](https://cloud.githubusercontent.com/assets/8238505/22062883/3fbeba3e-dd39-11e6-81d6-fcd4c25f2d8f.png)
![no installed in view](https://cloud.githubusercontent.com/assets/8238505/22062886/4182fb14-dd39-11e6-8c4a-7b6c62efba87.png)

**Comment by quanglam2807** [comment]
@rycon This is strange. It works normally for me on Manjaro. Does WebCatalog show you which apps are installed in home page?

**Comment by rycon** [comment]
Yea it does show the installed apps.  That's weird.

**Comment by quanglam2807** [comment]
@rycon. Can you open developer tools (Views >  Toggle Developer Tools), then go to Network.

Next go to Installed page (or click the refresh button if you are already there), there'll be a new request appears on the Network tab. Right click and then copy as cURL so I can investigate :)

![](http://i.imgur.com/X4cpnc8.png)

**Comment by rycon** [comment]
Here you go!

curl 'http://pfl0lpv96s-dsn.algolia.net/1/indexes/*/objects?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.20.4&x-algolia-application-id=PFL0LPV96S&x-algolia-api-key=2b9f5f768d387b7239ce0b21106373e9' -H 'Origin: file://' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-GB' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) WebCatalog/2.8.0 Chrome/53.0.2785.143 Electron/1.4.14 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: application/json' -H 'Connection: keep-alive' --data '{"requests":[{"indexName":"webcatalog","objectID":"chrome-gaedmjdfmmahhbjefcbgaolhhanlaolb-Default"},{"indexName":"webcatalog","objectID":"chrome-gbchcmhmhahfdphkhkmpfmihenigjmpp-Default"},{"indexName":"webcatalog","objectID":"chrome-nmmhkkegccagdldgiimedpiccmgmieda-Default"},{"indexName":"webcatalog","objectID":"microsoft-teams"},{"indexName":"webcatalog","objectID":"onedrive"},{"indexName":"webcatalog","objectID":"whatsapp"}]}' --compressed

**Comment by rycon** [comment]
It's working now!

Just a heads up that the homepage hasn't been updated with the 2.8.1 files I had to manually update the url to get the latest installers.

**Comment by quanglam2807** [comment]
@rycon Fixed!! Thank you for letting me know.

**Comment by quanglam2807** [comment]
This bug still occurs on Windows.

```
Hello Quang,

I knew your application through the website ghacks.net and I find it great.

But on my two computers under Windows 10 Pro, I have the same problem as described in case # 29 (for Linux) on your GitHub repository: Installed applications do not appear in Webcatalog, they are usable but I can not update them via the software.


Installed apps

![2017-11-17 11_03_36-webcatalog 2](https://user-images.githubusercontent.com/1548835/32947392-3e4506fc-cbce-11e7-8999-288064945790.png)
![2017-11-17 11_00_31-webcatalog](https://user-images.githubusercontent.com/1548835/32947394-3f089d56-cbce-11e7-8555-1181d7ed9852.png)
![2017-11-17 10_55_12-c__users_frederic nodier_appdata_roaming_microsoft_windows_start menu_programs_w](https://user-images.githubusercontent.com/1548835/32947401-404904d0-cbce-11e7-801f-452c9c936da5.png)


I am running Windows 10 Pro, the last WebCatalog 7.6.0  and I use Zemana AntiMalware which I disable because it detects WebCatalog as a malware.

What should I do?

Thank you for your reply.

Regards.



Frédéric NODIER
```
