### ISSUE TITLE
Apps won't open after installation.

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#3]
This happens for all applications installed via WebCatalog 2.2.0. 
```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

```

As an example here is what happens when trying to launch gitter:

```
open ~/Applications/WebCatalog Apps/Gitter.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/jonas/Applications/WebCatalog Apps/Gitter.app.
```

**Comment by quanglam2807** [comment]
@jottr I think it's because you haven't installed WebCatalog permanently to /Applications. Am I correct?

**Comment by jottr** [comment]
Nope, I installed the dmg. 

```
$ ls /Applications | grep -i webcatalog

WebCatalog 2.app

```

**Comment by quanglam2807** [comment]
@jottr Just rename `WebCatalog 2.app` to `WebCatalog.app` and everything will work normally! Still, I don't know why the app name is `WebCatalog 2` :)

**Comment by jottr** [comment]
Weird indeed. 
Anyways, renaming the app fixed it. Thx.
