### ISSUE TITLE
Browser controls

### ISSUE THREAD

**Issue by natrim** [quanglam2807/appifier#33]
would be nice to navigate the open app (webpage) via mouse clicks
ie. adding browser controls to right click menu (togglable in settings)
or adding controls to app titlebar

preferably both 
and ability to disable enable both or one

**Comment by quanglam2807** [comment]
@natrim What do you think about swipe to navigate? I think it's better to keep the app as simple as possible. For me, WebCatalog is more like an app container, not a browser.

**Comment by quanglam2807** [comment]
@natrim #1

**Comment by natrim** [comment]
swipe is useful for devices that have touch enabled controllers (touchpad, touchscreen, magic mouse) 
 but somewhat problematic if you want to control the app inside with only mouse
  and the app has no own way to get back one step
 (or sometimes the app sends you to some external page and you cannot get back)

i like how it is done in Colibri browser (https://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2016/11/ColibriHome.png)
the controls are normally invisible, but show up in titlebar if hover over him

but for Webcatalog would be probadly enough if there was back, forward and reload in right click menu as sometimes you want to go back or reload the app

or to make the swipe gestures work with right click and drag

**Comment by quanglam2807** [comment]
@natrim Colibri looks great but it would take a quite to implement similar functionalities as I need to redesign how WebCatalog works.

**Comment by natrim** [comment]
i know, thats why i said it would be ok if the controls were only in right click menu 
or trough right click gestures (like on opera, vivaldi or chrome with gestures plugin)

i guess it would be not too hard to create checkbox in settings that enables right click menu with back, forward and reload (and maybe home to get back on the app start page)
