### ISSUE TITLE
Allow for multiple users in G Suite

### ISSUE THREAD

**Issue by Rediwed** [quanglam2807/appifier#35]
Please add the ability to add a gmail/drive/calendar user!

Now it opens the auth page in safari, which doesn't report back to webcatalog that auth was succesful. Maybe it's an idea to open auth in a self contained window within webcatalog?

**Comment by quanglam2807** [comment]
Fixed! :)

**Comment by Rediwed** [comment]
Adding accounts works like a charm!
Except now, when switching between accounts it opens the new account in safari.. :(

(so when the new account is already added, and you want to switch it opens in new safari tab).

**Comment by quanglam2807** [comment]
@Rediwed I have fixed it in 2.8.4 but the solution might also affect other apps (both negatively and positively) so let's try and see.
