### ISSUE TITLE
OAuth doesn't work properly.

### ISSUE THREAD

**Issue by albertogcatalan** [quanglam2807/appifier#39]
If click on the Attach from Google Drive in Trello, WebCatalog goes blank page and cannot back to Trello. This problem is persistent when reinstall app :(

**Comment by quanglam2807** [comment]
It's quite similar to #31. I think it's because WebCatalog doesn't not reproduce window.open() API correctly.

**Comment by quanglam2807** [comment]
It also affects Moo.do

**Comment by ma1onso** [comment]
![screenshot from 2017-03-08 09-26-00](https://cloud.githubusercontent.com/assets/1877511/23709010/fa7c827a-03e5-11e7-84ae-d7c13352244a.png) feedly after the login with google

**Comment by quanglam2807** [comment]
@alons45 So many people emailed me about this bug. But it seems like a tricky one to resolve.

**Comment by quanglam2807** [comment]
electron/electron#8100

**Comment by quanglam2807** [comment]
I close this to clean up issues. This problem is related to https://github.com/electron/electron/issues/8969
