### ISSUE TITLE
Netflix does not play videos on OSX

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#4]
I see the following error, when trying to play a video:

`Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button.`

<img width="855" alt="screen" src="https://cloud.githubusercontent.com/assets/2744198/21596867/ad30dd4e-d141-11e6-92b3-4fd20b0e3183.png">

**Comment by quanglam2807** [comment]
The commit is up! It'll be fixed in the next update. @jottr, thank you for your feedback!
