### ISSUE TITLE
Ability to customise homepage

### ISSUE THREAD

**Issue by natrim** [quanglam2807/appifier#41]
It would be nice if we could define default page on the app in settings.

something like:
![home](https://cloud.githubusercontent.com/assets/488136/22874946/2fd2a33e-f1c9-11e6-91f7-e566d539cfed.png)

**Comment by quanglam2807** [comment]
@natrim I think this would be part of a progress to make WebCatalog a browser. A user also sends me a email asking to open URL with WebCatalog.

**Comment by natrim** [comment]
well, we are opening web apps so...
it's nothing so important though, i just wanted it to open certain vm in cloud9 on start

the alternative would be the issue #12 
i could just make it its own shortcut

edit: now that i think about it, i can make it custom shortcut right now without the advanced mode
 (just some copy paste and editing of existing shortcut to have another icon and name)
though the advanced mode would make it easier

**Comment by joethephish** [comment]
+1 For this. e.g. https://www.groovehq.com/ (which doesn't exist on WebCatalog right now) uses custom domains in the `yourdomain.groovehq.com` format.

**Comment by quanglam2807** [comment]
Will be available in the next update :)
