### ISSUE TITLE
Twitter login attempts fail

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#42]
3.0.2 beta on Mac. The request seems to fail when inspecting, see below:
<img width="711" alt="screen shot 2017-02-13 at 8 50 29 am" src="https://cloud.githubusercontent.com/assets/157270/22890446/9db34f2a-f1c9-11e6-97ec-69b4b692d38f.png">

It seems that upon re-launching the app I'm logged in if not using login verification. If the account uses login verification, I get texted the verification code, but I can never get redirected to the page that asks you to input it.

**Comment by quanglam2807** [comment]
@swrobel I think it's also related to #39

**Comment by swrobel** [comment]
This could be a possible solution: https://github.com/electron/electron/issues/3471#issuecomment-236368409

**Comment by quanglam2807** [comment]
@swrobel It works 👍
