### ISSUE TITLE
Apps force closed "Could not automatically determine the current application's identifier"

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#47]
Google Maps force closes immediately after launch. 
`Webcatalog Version 3.1.1 (3.1.1.235)`

Is there a means to display debug information for Webcatalog Applications?

**Comment by quanglam2807** [comment]
@jottr Can you try 3.2.5? It works normally for me.

**Comment by natrim** [comment]
happened the same to me in other apps, probably caused by crashing updater after release of 3.2.5
cause after manual update it works

Crashing on exception: Could not automatically determine the current application's identifier

**Comment by quanglam2807** [comment]
Thank you very much, @natrim. I have reproduced the bug. It's due the path of the alternative executable: https://github.com/webcatalog/desktop/blob/master/packager.js#L63

I'm working on a fix.
