### ISSUE TITLE
Can't login to Asana using Login with Google

### ISSUE THREAD

**Issue by eablokker** [quanglam2807/appifier#50]
The Google Login modal pops up for a second, then the main window displays the google login page. I enter my Google credentials, and then it asks me to enter my 2 factor authentication code. Once I do, it just takes me to a blank page. If I try to start over and login with google again, it just pops up the login modal for a second and then takes me right back to the blank page.

If I try to log in to another Google account that does not use 2 factor authentication, the same issue occurs.

I am able to login to my other Asana account if I login with my email, and everything there works fine.

**Comment by eablokker** [comment]
I immediately found a workaround. If you click the Forgot Password link in Asana when logging in (in a web browser), you can reset your password and it will convert your Google login to an Asana login.

> Asana Tip: If you currently log into your account via Google and want to switch to a password, request a password reset link.

[Source: Managing your Account Settings](https://asana.com/guide/help/fundamentals/accounts)

**Comment by quanglam2807** [comment]
It's similar to #39. It also affects Spotify's Facebook login. So at the moment, I think your idea to convert to password login is great! I'll close this issue as we can discuss in #39.

**Comment by quanglam2807** [comment]
I close this to clean up issues. This problem is related to https://github.com/electron/electron/issues/8969
