### ISSUE TITLE
Asana app not working?

### ISSUE THREAD

**Issue by joethephish** [quanglam2807/appifier#51]
Not sure whether it's because of the way authorisation works when you use a Google account, but Asana isn't currently working - after login, I just get a blank page :-(

It's a shame, because Asana recently stopped working in Fluid too, perhaps for similar reasons?

Great work on WebCatalog otherwise, love the concept!

**Comment by joethephish** [comment]
Ah, this may be a duplicate of #39.

**Comment by quanglam2807** [comment]
@joethephish Sadly, It's the same problem with #39. I'll close this issue so we can discuss in #39.
