### ISSUE TITLE
Google Tasks doesn't open correctly

### ISSUE THREAD

**Issue by rstacruz** [quanglam2807/appifier#52]
![image](https://cloud.githubusercontent.com/assets/74385/23647951/760cdd24-0353-11e7-8a6c-e91df901e4b5.png)

I'm guessing it goes to https://gmail.com/tasks, which only works if your User-Agent is a mobile device.

Nevertheless, this URL works better: https://mail.google.com/tasks/ig?pli=1

**Comment by quanglam2807** [comment]
@rstacruz Thank you very much for reporting. I have fixed it and you need to uninstall and reinstall Google Tasks.
