### ISSUE TITLE
Change window title and icon based on app

### ISSUE THREAD

**Issue by jnss95** [quanglam2807/appifier#53]
I'm currently on windows and using WebCatalog 3.2.7. It would be nice if the title bar icon and text would display the apps name and icon instead of "WebCatalog" and the WebCatalog Icon. Strangely the icon in the taskbar is displayed correctly.

**Comment by quanglam2807** [comment]
@Xeranor I haven't spent a lot of time on the Windows version yet. But I'll try to improve the UX and add this in the next update +1.

**Comment by quanglam2807** [comment]
@Xeranor Only page title can be updated as the API for icon doesn't work well enough. I'll close the issue.
