### ISSUE TITLE
Ad blocking

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#58]
Adblocking in webcatalog would be a nice to have for some sites, i.e. youtube.
Sadly electron won't support the Chrome extensions API. 
The [min-project](https://github.com/minbrowser/min) solved this by creating a custom [abp-filter-parser](https://github.com/minbrowser/min/tree/master/ext/abp-filter-parser-modified).

**Comment by quanglam2807** [comment]
@jottr This is awesome! Actually adp-filter-parser is only to determine which requests to be blocked. This is the [needed code](https://github.com/minbrowser/min/blob/0a07a99415d8670e49c03a6e12d76a427784964e/main/filtering.js)

**Comment by quanglam2807** [comment]
:) Tada! Done.

**Comment by jottr** [comment]
It seems that adblocking has been removed from Webcatalog.
I'd like to kindly request this to be readded to webcatalog. :)
@quanglam2807

**Comment by quanglam2807** [comment]
I'm testing Ad-blocking with a new app Secreton: https://secretonapp.com/. If it's stable enough, I'll merge the feature to WebCatalog.
