### ISSUE TITLE
Turn WebCatalog into an app store

### ISSUE THREAD

**Issue by max-pub** [quanglam2807/appifier#59]
I think you project is awesome! 
You should include way more apps though and position this thing as an AppStore equivalent for WebApps!
maybe register something like webapp.store?

**Comment by quanglam2807** [comment]
@max-pub I will try to make a page to show all the apps on the website. But I think WebCatalog would be a better branding as Web App Store sounds very general. Also, webapp.store costs 6500 USD.

**Comment by max-pub** [comment]
the naming is secondary...

more important is to support thousands of apps instead of just a few...

and maybe highlight the webapps that can be used offline...

**Comment by quanglam2807** [comment]
@max-pub Actually, right now, the backend I use for the app (https://github.com/webcatalog/backend) is very basic. I'm also planning to turn it into an app store but I will need to rewrite the backend. Having a proper backend will also allow WebCatalog to run on mobile devices (https://github.com/webcatalog/mobile). I'll try to start working on it during the summer as I am quite busy now. At the moment, I'll concentrate on fixing bugs and fulfilling basic features. If you participate in the project, it would be awesome.

**Comment by jottr** [comment]
The people of [wmail](https://thomas101.github.io/wmail/) are doing something quite interesting with their project, renaming it to [wavebox](https://wavebox.io), keeping it on github but also trying to monetise ist at the same it.   
They seem to position wavebox as some sort of app store.  
Not sure if it's a smart move, but interesting to watch nonetheless.

**Comment by quanglam2807** [comment]
@jottr I am considering to do the same thing. I will keep the app open source, even the paid features. Of course, somebody can just fork the project and make it completely free but very unlikely. The money will allow me to run a proper Node.js backend instead of relying on GitHub and CI. But first, I will try to improve the app. +1
