### ISSUE TITLE
Add zattoo.com

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#6]
[zattoo.com](https://zattoo.com) would be a neat addition to webcatalog!

**Comment by quanglam2807** [comment]
@jottr Do you have a good icon for the app? The one on Google Play Store looks terrible.

**Comment by jottr** [comment]
I've got an [.icns](http://ge.tt/6JCqDCi2) I created for nativefier earlier.
Note, that they must be using some form of DRM. 
I've tried creating an electron app earlier, but some channels are not available when using electron. 
Chrome works fine though. 
Maybe this is a similar issue as with netflix?

**Comment by quanglam2807** [comment]
@jottr That ICNS has low resolution so I'll use another one I've found with Google Images. It's not perfect but acceptable. 👍 

Also, I am not sure about the issue you mentioned at all. Let's add it to the catalog first and test then  :) And actually, star the project please! I'm desperate.
