### ISSUE TITLE
Missing Code Signing Certificate (Windows)

### ISSUE THREAD

**Issue by outwitevil** [quanglam2807/appifier#60]
![symantec_webcatalog](https://cloud.githubusercontent.com/assets/294029/23770686/07745de8-04e2-11e7-9110-e8ef0dfe9a11.png)

Didn't see this mentioned anywhere else on here.
Not sure why but Symantec Endpoint Protection doesn't seem to like you.

**Comment by jottr** [comment]
I don't see the point of optimising this application to play nice with antivirus snakeoil. 
Even more so since [WS.Reputation.1](https://www.symantec.com/en/uk/security_response/writeup.jsp?docid=2010-051308-1854-99) simply gave you a false positive.

**Comment by outwitevil** [comment]
I don't disagree but I cannot disable it.

**Comment by quanglam2807** [comment]
@outwitevil This is because the app is not signed with proper certification. It would cost around 300 USD a year.

https://github.com/electron-userland/electron-builder/wiki/Code-Signing
https://msdn.microsoft.com/windows/hardware/drivers/dashboard/get-a-code-signing-certificate
