### ISSUE TITLE
Need contributors to help adding apps.

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#61]
The number of users is growing pretty fast and there are a lot of app submissions. But at the moment, all the apps need to be added manually and I need somebody to help me with this.

**Comment by natrim** [comment]
its just adding json and image to https://github.com/webcatalog/backend right?

i don't mind helping when i have some time

**Comment by quanglam2807** [comment]
@natrim Precisely. But I need to give you access to the Google Spreadsheet form. Do you use WhatsApp, Facebook Messenger or Skype?

**Comment by natrim** [comment]
sent you mail

![dash_glass100](https://cloud.githubusercontent.com/assets/488136/24012570/c3d68212-0a7e-11e7-931f-93e769a705b8.png)
