### ISSUE TITLE
Password Manager support

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#64]
> I’d like it to be able to save passwords directly, or add 1Password and/or Apple Keychain support so I don’t have to enter my password for Mint every time.

**Comment by quanglam2807** [comment]
Related to https://github.com/webcatalog/molecule/issues/4

**Comment by cmer** [comment]
I'd love to see support for 1Password on macOS as well. I'm not sure what the status of this request is since it was closed and the related issue doesn't give much more info. Thanks!

**Comment by quanglam2807** [comment]
Hi @cmer, the reason why I linked the issue to another repo because I'm planning to debundle the app into multiple packages. At the moment, Electron which the app relies on does not support Chrome extensions so it is quite challenging to add this feature. But as soon as we finish debundling the app, it is possible to add this feature as we can replace Electron with https://github.com/brave/muon which supports Chrome extensions (including 1Password). 

Still, the project is growing and we are planning on many cool features so it will take some time.
