### ISSUE TITLE
Plank dock shows WebCatalog apps as the same grouped app with default icon

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/appifier#69]
> Plank dock shows WebCatalog apps as the same grouped app with default
icon. Could You please fix that issue?

![x](https://cloud.githubusercontent.com/assets/1548835/23927839/3cc7b9b6-08ea-11e7-842e-e04ae5bc4b8b.png)

**Comment by miosz** [comment]
It happened on Linux Mint with Xfce Desktop Environment.

**Comment by quanglam2807** [comment]
@miosz It seems tricky as I cannot reproduce the bug on Ubuntu Unity and elementaryOS. Installing Xfce now.

**Comment by quanglam2807** [comment]
@miosz Ok. I think it's because of how Plank detects app launch from the menu. It works normally with the task bar on Linux Mint.

And if you launch an app from WebCatalog, it works normally.

<img width="1280" alt="screen shot 2017-03-18 at 7 01 28 pm" src="https://cloud.githubusercontent.com/assets/1548835/24077019/c1258474-0c0d-11e7-92b7-776428d51dfe.png">

**Comment by quanglam2807** [comment]
WebCatalog use `gtk-launch` command https://github.com/webcatalog/webcatalog/blob/f469a4bdca30b7909f8c9a51c3799003914f55f1/ui/store/components/Card.js#L59

**Comment by miosz** [comment]
How can I help You to solve the issue? I Was using Fogger before WebCatalog and icons were shown normally.

**Comment by quanglam2807** [comment]
@miosz WebCatalog works differently from Fogger, Nativefier and Fluid. For example, if you install an app from Fogger, it will generate completely independent Linux package but WebCatalog only installs a shortcut (linked to itself with some specific instructions). 

I think the best way is to contact somebody from the Plank development team so we can discuss how to implement the shortcut correctly. Because if it works with the taskbar but not with Plank, I guess it's because doesn't use standard Linux API.

**Comment by miosz** [comment]
I have updated Plank to newest version but it didn't solve the case. Maybe libplank API documentation could help You to solve the issue? http://people.ubuntu.com/~ricotz/docs/vala-doc/plank/index.htm

**Comment by quanglam2807** [comment]
@miosz It doesn't help at all. Can you contact Plank development team or provide me a way to contact them?

**Comment by miosz** [comment]
Answer contacts for Plank
Rico Tzschichholz
https://launchpad.net/~ricotz

**Comment by adambowles** [comment]
Same thing occurs in Gnome3, all my WebCatalog apps are grouped in one entry in the dock.

**Comment by miosz** [comment]
@quanglam2807 did you worked it out?
Today I have installed Gmail app and noticed that Plank displayed proper icon in dock.
I have uninstalled and installed Hangouts and now it works fine :)
![przechwycenie obrazu ekranu_2017-04-06_21-11-19](https://cloud.githubusercontent.com/assets/26469183/24771381/b93b2f5c-1b0d-11e7-8821-d10cd18424f8.png)

**Comment by quanglam2807** [comment]
@miosz That's weird. I haven't changed anything.

**Comment by miosz** [comment]
@quanglam2807 excuse me, seems like it works only for the first run:
![przechwycenie obrazu ekranu_2017-04-06_21-32-42](https://cloud.githubusercontent.com/assets/26469183/24772189/a461c520-1b10-11e7-9ae6-ee1c83ea0d55.png)
To make it work You have to "pin" icon after first run.

**Comment by miosz** [comment]
Additional info - webcatalog app is shown as grouped gmail icon (two dots):
![przechwycenie obrazu ekranu_2017-04-07_00-00-46](https://cloud.githubusercontent.com/assets/26469183/24777365/5757f6fe-1b25-11e7-97e2-21ef00325d3f.png)

**Comment by quanglam2807** [comment]
Should be fixed in the next release. If not, I will reopen the issue.

**Comment by quanglam2807** [comment]
@miosz This should be fixed with #141
