### ISSUE TITLE
Windows 64-bit version of 3.4.0 not working

### ISSUE THREAD

**Issue by adioni** [quanglam2807/appifier#74]
After webcatalog is setup and I install, for example 'Google Inbox', clicking Open does nothing. If I navigate to `%userprofile%/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/WebCatalog Apps` and double click on the shortcut there, it says it cannot find `webcatalog.exe`

Version 3.3.0 works fine.

**Comment by quanglam2807** [comment]
@adioni This is a very serious bug. I'll try to fix it ASAP.

**Comment by quanglam2807** [comment]
It's because I added 32-bit support and the build script messed up the Setup file. Thanks for reporting :)
