### ISSUE TITLE
Status bar or other method to see the URL of links

### ISSUE THREAD

**Issue by swrobel** [quanglam2807/appifier#82]
Just like Chrome will show the URL of a link on hover in the bottom left, it would be nice to have the same in WebCatalog.

<img width="560" alt="screen shot 2017-03-20 at 8 36 17 am" src="https://cloud.githubusercontent.com/assets/157270/24107572/58b04bea-0d48-11e7-8465-6ba837c5965c.png">

**Comment by quanglam2807** [comment]
@swrobel It seems like WebCatalog is turning into a browser :)

**Comment by swrobel** [comment]
It's useful to know if the link is going to open in the current WebCatalog app or the default browser: https://github.com/webcatalog/webcatalog/blob/master/src/ui/ssb/components/App.js#L135

**Comment by quanglam2807** [comment]
Tada :)
