### ISSUE TITLE
draw.io struggling with Google Drive authentication

### ISSUE THREAD

**Issue by jordancohn** [quanglam2807/appifier#86]
The page opens for a second and closes again. I think it's similar to other bugs but not sure how to work around it..
<img width="1281" alt="screen shot 2017-03-23 at 5 04 22 pm" src="https://cloud.githubusercontent.com/assets/12727765/24234120/c8dd658e-0fea-11e7-8342-78207cc7d41f.png">

**Comment by quanglam2807** [comment]
@jordancohn I've found a fix for this bug. It wouldn't take too long :)

**Comment by jordancohn** [comment]
can't wait! will make my life a whole lot easier and thank you for this app 🙂

**Comment by quanglam2807** [comment]
I close this to clean up issues. This problem is related to https://github.com/electron/electron/issues/8969

**Comment by vlad-cotfas** [comment]
@quanglam2807  Hello, Any news on this? How can I log in? Thank you!

**Comment by stefanq** [comment]
draw.io is fantastic but I cannot use it with Google drive due to this issue.
On any authentication attempt a small empty white window shortly pops up only to disappear after about 100ms.
I'm using Version 65.0.3322.3 (Offizieller Build) dev (64-Bit) on linux.
Are there any workarounds?

**Comment by quanglam2807** [comment]
@stefanq As I mentioned, it's related to https://github.com/electron/electron/issues/8969. I can remove the sandbox feature but it would affect the security of the app.
