### ISSUE TITLE
Adds Homebrew cask update automation

### ISSUE THREAD

**Issue by jottr** [quanglam2807/appifier#91]
Just a heads-up:

I'm making this an issue, since I wouldn't know where else to put it. 
Sadly homebrew still requires us to manually bump the cask version on each new release. 
I'm currently doing this with the `cask-repair`-script, as per the homebrew [documentation](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

Maybe `cask-repair` should be run on each new release. Should we automate this?

**Comment by quanglam2807** [comment]
@jottr The command look quite confusing for me.  Can you make a PR?

**Comment by jottr** [comment]
I'm in the process of figuring out if there is a better method than the `cask-repair` script for automated pull-requests.

**Comment by adidalal** [comment]
You can script `cask-repair` (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

For example, after performing a release, just run
`cask-repair -b -v {{new_version}} webcatalog` - that'll update the Cask file and open up a PR in HBC (which should be quickly merged) for you.

**Comment by jottr** [comment]
Thx @adidalal, I was hoping to find a method which requires less dependencies. I.e. `cask-repair` installs `hub` if it isn't installed.

**Comment by adidalal** [comment]
Hub is used to do auto-forking of the repo, IIRC. You should be able to pull a slightly older version from the tinyscripts repo, that shouldn't have any dependencies.

**Comment by quanglam2807** [comment]
@jottr @adidalal  Are you still interested in this issue?

**Comment by jottr** [comment]
Yes. I'm currently sending manual [PRs](https://github.com/caskroom/homebrew-cask/pull/39931) once I discover a new version is online. I'd prefer that this be automated.
