### ISSUE TITLE
Missing icon in Fedora / Gnome3

### ISSUE THREAD

**Issue by adambowles** [quanglam2807/appifier#95]
OS: Fedora Linux 4.4.14-200.fc22.x86_64
Gnome-shell version: GNOME Shell 3.16.4

Installed via `.rpm` package

![screenshot from 2017-04-05 10-55-53](https://cloud.githubusercontent.com/assets/10128574/24700276/89cfc252-19ee-11e7-8eeb-6177b52c2d24.png)

(That YNAB is installed via WebCatalog fyi)

**Comment by quanglam2807** [comment]
@develar Is this bug related to `electron-builder`?

**Comment by develar** [comment]
@quanglam2807 Does it work on ubuntu?

**Comment by quanglam2807** [comment]
The last time I tested, I worked. I'll try again so you don't need to waste your time.

**Comment by quanglam2807** [comment]
@develar It works normally with Ubuntu (.deb)

**Comment by quanglam2807** [comment]
I'm not really sure if this issue has been fixed with `electron-builder` or not. But I'll close this issue to clean up the repo. Please let me know if it still doesn't work correctly.

**Comment by luisca-dev** [comment]
It doesn't show the icon in the "dash to panel" extension for GNOME.
The icon showed is the one next to Skype.
![image](https://user-images.githubusercontent.com/15930014/31354009-54d4553c-acfa-11e7-8b20-974ea272c45d.png)

**Comment by quanglam2807** [comment]
@winuxue What version are you using?
