### ISSUE TITLE
Needs a way to regenerate icons or reinstall app shortcut

### ISSUE THREAD

**Issue by natrim** [quanglam2807/appifier#96]
Well one weird bug here.

On windows i cleaned my disk with Disk Cleaner (its a default W. app)

And all icons in webcatalog shortcuts are gone.

So i tried unistalling them and then adding them back, which sadly removed all app data.
So it would be nice to have reinstall button which will not remove the app data and then uninstall and install the app anew.
(ie. dont remove the "persist:" storage )

Plus when i readded Dropbox Paper the icon in bar is now broken.

![schranka 01](https://cloud.githubusercontent.com/assets/488136/24835766/2809969a-1d0b-11e7-8b24-16d2fd66a0c4.png)

**Comment by quanglam2807** [comment]
@natrim The icons are stored in temp folder so they are deleted by Disk Cleaner. I'll move them to a persistent location and everything will be fixed.

**Comment by natrim** [comment]
ok

just update on the missing paper icon
the icon sudenly apeared
![schranka 02](https://cloud.githubusercontent.com/assets/488136/24838756/bdbbf0b4-1d4e-11e7-9d6d-e67adc4c443a.png)

but it has weird black fragments (and the gitter gained them too though before it was ok)
its probadly some unfixable weirdness in windows

**Comment by quanglam2807** [comment]
@natrim Wait for 4.1.1 :)

https://github.com/webcatalog/webcatalog/releases/tag/v4.1.1

**Comment by natrim** [comment]
![derpyderp100](https://cloud.githubusercontent.com/assets/488136/24839368/5fc499ec-1d59-11e7-8b8f-89b2bf745191.png)

**Comment by natrim** [comment]
@quanglam2807 ok i updated to the 4.1.1 alpha and the updating does not work .)

it says Update error: Cannot find module 'js-yaml'

(it even says the same during installing of new app)

plus apps have no titlebar and error

Uncaught TypeError: Cannot read property 'then' of null
    at window.onload (AppData\Local\Programs\WebCatalog\resources\app.asar\app\preload.js:1)
core_external.current.Y0wYWDWu3W7E8nQSncf6Noa2jJv8xuwtM7TOx5FK1EM.js.gz:403 

JQMIGRATE: jQuery.parseJSON requires a valid JSON string
r @ core_external.current.Y0wYWDWu3W7E8nQSncf6Noa2jJv8xuwtM7TOx5FK1EM.js.gz:403
core_external.current.Y0wYWDWu3W7E8nQSncf6Noa2jJv8xuwtM7TOx5FK1EM.js.gz:403 
console.trace
r @ core_external.current.Y0wYWDWu3W7E8nQSncf6Noa2jJv8xuwtM7TOx5FK1EM.js.gz:403

OS is W10x64

**Comment by quanglam2807** [comment]
@natrim Copy that. There's something wrong with the build process.
