### ISSUE TITLE
Icon Issue on Windows & Task  Bar - KDE Neon - (Ubuntu 16.04)

### ISSUE THREAD

**Issue by Paulser** [quanglam2807/appifier#97]
Icon Issue on windows and task bar. It shows the default icon. Picture example of issue is below. 

![screenshot_20170411_005707](https://cloud.githubusercontent.com/assets/20326940/24887311/ba6dcedc-1e52-11e7-896b-147573da84a5.png)

The system has the icons in the menu system on KDE Neon fine. I have added a gif file to show the icons below. 

![correcticonsonsystemmenu](https://cloud.githubusercontent.com/assets/20326940/24887570/92ade862-1e54-11e7-8460-1f54425ef8ea.gif)

It is a strange issue because it seems to load the icon on the task bar for a few second then change back to the default icon. I have added a gif file to show the issue I am having below. 

![iconissuekde](https://cloud.githubusercontent.com/assets/20326940/24887473/e7ed2ae6-1e53-11e7-9706-7c84babaef40.gif)

Thanks for reading this issue

Kind Regards,
Paul Serafini

**Comment by quanglam2807** [comment]
Looks similar to #69. Can you try 4.1.1 (alpha) and let me know if it works?

**Comment by Paulser** [comment]
@quanglam2807 Yes of course please provide the download link for alpha? I am reviewing your website for it. 

Thanks for the support

**Comment by quanglam2807** [comment]
@Paulser https://github.com/webcatalog/webcatalog/releases/tag/v4.1.1
Thank you very much. :)

**Comment by Paulser** [comment]
@quanglam2807 I am having a loads other graphical problems with the app now but it is an alpha. I try again but I do complete purge and maybe restart before reinstalling. I have not managed to reinstall an app yet to test alpha.

**Comment by Paulser** [comment]
@quanglam2807 I cant seem to get any app installed through the alpha sorry. Want me to raise another issue for the alpha since it not really related?

**Comment by quanglam2807** [comment]
@Paulser  I'll start debugging. You don't need to create another issue. It's fine. I made some critical changes so some problems occur.

**Comment by Paulser** [comment]
@quanglam2807 I have to go at the moment. I will review this report later thanks for the support.

**Comment by Paulser** [comment]
tested: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.2

@quanglam2807 I have tested this issue on Windows & Ubuntu. The icon on the window is now not an issue because in the alpha you have removed the icon on the left of the windows. which looks good. 

I am still getting the same issue that icons are not appearing in the task bar for Windows 10 & KDE Neon Ubuntu 16.04.

Examples are below.

Windows 10:

![noiconsontaskbarwindows10](https://cloud.githubusercontent.com/assets/20326940/24934917/868bf336-1f16-11e7-9453-6fa81b7a3790.gif)

Ubuntu 16.04:

![taskbariconnotchanging](https://cloud.githubusercontent.com/assets/20326940/24935463/254ec220-1f1a-11e7-9982-7c071ec4e990.gif)

Icon does not load at all if you try open app through web store instead of OS application menu.

![ubuntuiconchangetwo](https://cloud.githubusercontent.com/assets/20326940/24935557/acac4486-1f1a-11e7-8619-dbd926d13ad2.gif)

**Comment by Paulser** [comment]
Tested: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.3

Windows 10 - Each app has got it's own icon that works really well on this update. (Shame I do not use the OS that often)

![windowsiconsworks](https://cloud.githubusercontent.com/assets/20326940/24974867/92ef2116-1fbb-11e7-96de-52671601270b.gif)

Ubuntu 16.04 (KDE Neon) - Icon issue still on this update on Ubuntu 16.04 KDE Neon. 

![iconsnotchangeintaskbar](https://cloud.githubusercontent.com/assets/20326940/24975980/9453a7b2-1fbf-11e7-9dad-c1a5a566391e.gif)

**Comment by Paulser** [comment]
@quanglam2807 

Tested: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.4

Ubuntu KDE Neon - User Edition - Plasma 5.8 Desktop

Same issue as reported on v4.1.3 icons not appearing on task bar. 

Also icons not splitting from each other but this not big issue.

**Comment by Paulser** [comment]
@quanglam2807 

Tested: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.5

Ubuntu KDE Neon - User Edition - Plasma 5.8 Desktop

Same issue as reported on v4.1.3 icons not appearing on task bar.

Also icons not splitting from each other but this not big issue.

**Comment by Paulser** [comment]
@quanglam2807 

Just update quick update this issue still exists. 

Ubuntu KDE Neon - User Edition - Plasma 5.8 Desktop

![iconsdontsplit](https://user-images.githubusercontent.com/20326940/27555433-a236b8fe-5aa9-11e7-818e-a0d02a75ddf1.gif)

Would like each app to be split on the task bar with different icons if possible.

Works great and I am enjoying using it.

**Comment by quanglam2807** [comment]
Thank you very much, @Paulser. It should be fixed with #141
