### ISSUE TITLE
Cannot set property 'forceClose' of undefined

### ISSUE THREAD

**Issue by hubbuddy1** [quanglam2807/appifier#98]
![screen shot 2017-04-11 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/6365356/24927285/870d2068-1ecc-11e7-80bb-e3a0af79e515.png)

**Comment by quanglam2807** [comment]
@jasjeet86 Thanks for your donation :). What version are you using?

**Comment by hubbuddy1** [comment]
You deserve more donations . 4.0.3

**Comment by quanglam2807** [comment]
Fixed in 4.1.
